Migrate multi-inclusive volumes how-to from Knowledge Base to product-docs
emnify/product-docs pull request #100
Opened 2023-03-09 16:28 UTC by carolstran

### Description

When working on the subscription page tooltips, the only guide we could link to related to the “Multi-inclusive volumes” feature was [one in our Knowledge Base](https://support.emnify.com/hc/en/community/posts/5287107334556-How-to-set-up-multi-inclusive-volumes-).

This guide has the outdated brand design and is generally something that is better suited for our product documentation, so this PR migrates/restructures the guide and verifies the the content is up-to-date ✨ 

> ℹ️  _**Note:** This guide has also been sent to Bas (Growth PM) and the CSM team for a functional review._

### Additional Context

Internal ticket 🎟️ [PGR-226](https://emnify.atlassian.net/browse/PGR-226) (parent story: [PGR-208](https://emnify.atlassian.net/browse/PGR-208))

2023-03-10 08:46 UTC, techwriter-dev requested changes
Added some suggestions.

2023-03-10 08:46 UTC, techwriter-dev commented on docs/how-tos/multi-inclusive-volumes.md
> +These changes have an impact on your monthly bill.
```suggestion
These changes will have an impact on your monthly bill.
```
or

```
Could affect your monthly bill.
```

2023-03-10 08:46 UTC, techwriter-dev commented on docs/how-tos/multi-inclusive-volumes.md
> +2. Scroll down to your **Coverage Policies**
Perhaps this is another opportunity to add additional internal anchors that reflect the structure beneath **Device Policies** which would eliminate these first 2 steps through the use of a single link:

- `#service-policies`
- `#coverage-policies`

![device-policies-structure](https://user-images.githubusercontent.com/49970529/224267137-444457ba-9746-408c-89d0-6972ee960913.png)

2023-03-10 09:34 UTC, carolstran commented on docs/how-tos/multi-inclusive-volumes.md
> +2. Scroll down to your **Coverage Policies**
Yes we have a ticket for this open in Growth squad! That said, we already know what the anchors will be so I can already add them as part of this task good catch 🙌🏼

2023-03-10 10:48 UTC, carolstran commented
FYI @techwriter-dev: Received a bunch of feedback from Jean-Eudes (Director of Customer Success, [see Slack thread](https://emnifyteam.slack.com/archives/C27MUBN4S/p1678442224043269)) so I'll update with his feedback and make sure it's approved before I ping for a final code review 😇

2023-03-15 15:05 UTC, carolstran commented
Alright finally ready for a re-review @techwriter-dev 😅 🚀

2023-03-16 12:38 UTC, techwriter-dev commented
> @techwriter-dev If you have any tips for optimizing the images without messing up the quality, let me know 😅 I did my best but they're still big/don't look the best 🙃

@carolstran There is no perfect solution. Taking the following example, I recreated the image (showing different devices) and placed it under yours. The only difference is I set my browser to zoom in at 125% before taking the screenshot. If I can get it to fit, I sometimes zoom in to 150%. The goal is to have an image that comes as close to possible to the sweet spot of 915 pixels wide. That's the horizontal limit of Docusaurus for images on a standard monitor (1920 x 1080) in fullscreen mode. On a MacBook the default display is resampled to (1512 x 982).

Here's the **flip side**: when you use the **click-to-zoom-in feature** we've deployed, _your_ image will look much better than my zoomed-before-capture one. However, for whatever reason, on page load the resampling of much larger images like yours is more lossy that the smaller one I produced. 

![img-zoom-comparison](https://user-images.githubusercontent.com/49970529/225615110-553136d8-eeca-4d76-944a-4608efed5377.png)

2023-03-16 12:41 UTC, techwriter-dev approved these changes
I left some comments, but they're not blocking.

2023-03-16 13:34 UTC, carolstran commented
@techwriter-dev Thanks for sharing more about the images! I managed to decrease the image size since writing that and it's not ideal but ok for now (IMO). 

Makes me think we should pull up the ticket we have about optimizing images up in priority though bc it could be worth finding a better, even automated process for this 🤔

2023-03-16 16:48 UTC, carolstran commented
Note about this PR: Waiting on a final OK from Bas about how we mentioned the Pro/Plus plans. Once I get the ✅ from him, I'll merge 🥳

2023-03-19 00:40 UTC, merged