Add an entry for SIM in the Glossary
emnify/product-docs pull request #102
Opened 2023-03-12 19:59 UTC by techwriter-dev

### Description

Add an entry for **SIM** in the Glossary.

Based on feedback from Bas: There’s no definition for “SIM” in our Glossary but there are other related terms. 

Internal 🎫 [SDOCS-238](https://emnify.atlassian.net/browse/SDOCS-238)

2023-03-14 21:11 UTC, carolstran requested changes
Overall looks good (assuming it's been reviewed by an SME because I can't speak to the accuracy 😅 ) - just needs a couple changes before merging!

2023-03-14 21:11 UTC, carolstran commented on docs/glossary.md
> +A SIM (Subscriber Identification Module) an integrated circuit (IC) available as a card in various form factors that stores data used to identify a subscriber ([IMSI](#imsi---international-mobile-sub
```suggestion
A subscriber identification module (SIM) is an integrated circuit (IC) available as a card in various form factors that stores data used to identify a subscriber ([IMSI](#imsi---international-mobile-subscriber-identity)) along with other network information for connecting and authenticating with a [mobile network operator (MNO)](https://www.emnify.com/iot-glossary/mno).
```

What I'm suggesting:
- Flip the word order so that it's written out then the acronym is introduced in parenthesis (consistent with the other glossary terms)
- A couple typo fixes (add missing `is`, remove double `other`)

Then a couple questions:
1. I know "IC" is an industry acronym, but it doesn't seem like emnify's used it anywhere else. Should we still include it here or will it potentially cause confusion? Or, should we add a glossary entry for this specifically? 🤔 
1. Would it be possible to break this up into two sentences? The description makes sense as-is, but breaking it up might increase readability 💡

2023-03-14 21:11 UTC, carolstran commented on docs/glossary.md
> +The [emnify eSIM](/services/global-iot-sim) has capabilities not available with other eSIMs.
IMO this should be a separate glossary entry so that we can specifically link to it. Wdyt? 

Then non-blocking, but it'd be nice to add some examples of the emnify eSIM's capabilities so that people are curious to read more 😊

2023-03-15 12:11 UTC, techwriter-dev commented on docs/glossary.md
> +The [emnify eSIM](/services/global-iot-sim) has capabilities not available with other eSIMs.
> Then non-blocking, but it'd be nice to add some examples of the emnify eSIM's capabilities so that people are curious to read more 😊

This is why I supplied the [emnify eSIM](https://github.com/emnify/product-docs/blob/SDOCS-301-global-iot-to-emnify-sim/docs/services/global-iot-sim.md) link where the reader learning more about it, including the multi-IMSI application.

2023-03-15 15:25 UTC, carolstran commented on docs/glossary.md
> +The [emnify eSIM](/services/global-iot-sim) has capabilities not available with other eSIMs.
Sorry if you already replied to this and I just didn't see it 🤪  but do you think eSIM should be its own glossary entry? Thinking esp since we're going to be referring to it a lot 🤔

2023-03-15 18:09 UTC, carolstran approved these changes
Thanks for your patience with my questions! Looks good on my end ✅ 🎉  (assuming its been reviewed by a SME 😅)

2023-03-15 22:20 UTC, merged