Publish initial GraphQL API documentation
emnify/product-docs pull request #107
Opened 2023-03-15 14:28 UTC by carolstran

### Description

First pass at GraphQL API documentation so we can share the GraphiQL IDE and collect feedback. 
The plan is to continue adding to and improving this section 👷🏼‍♀️ 

What's in this PR:
- New `GraphQL API` section of the docs site
- Page outlining that the GraphQL API is in preview mode
- Guide to walk people through how to use the GraphiQL IDE

### ✨  Visual preview 

<img width="1126" alt="Screenshot 2023-03-15 at 15 22 59" src="https://user-images.githubusercontent.com/26869552/225338719-3710bcdc-6916-4279-a919-fad7327d4d0d.png">

### Known issue 

🙈  (but would 10/10 prefer to open a follow-up bug than block merging with this)
<img width="488" alt="Screenshot 2023-03-15 at 15 26 53" src="https://user-images.githubusercontent.com/26869552/225340000-045d2169-57be-4f37-aefa-723d518c7bfc.png">

### Additional Context

Internal (parent) ticket 🎟️ [CI-1909](https://emnify.atlassian.net/browse/CI-1909)

2023-03-15 14:31 UTC, carolstran commented
Can't tag you directly as a reviewer so 👀 @AmrAnwar 😈

2023-03-15 17:01 UTC, AmrAnwar commented
This image you use at the begining is quiet old, better to use another on.
![image](https://user-images.githubusercontent.com/25433336/225377124-c78e9280-b158-43dc-a9f2-fbd84c3da744.png)

-- This is new one for you:
![image](https://user-images.githubusercontent.com/25433336/225385087-37c5fa5c-4b23-4fca-a1b5-675974392473.png)

2023-03-16 10:10 UTC, techwriter-dev requested changes
Just a couple of suggestions to consider.

2023-03-16 13:47 UTC, techwriter-dev approved these changes

2023-03-16 16:39 UTC, merged