Create workspaces how-to category and publish switching between workspaces guide
emnify/product-docs pull request #115
Opened 2023-03-29 15:23 UTC by carolstran

> **Warning**
> _Current PR is pointing to the `workspaces-how-to` branch as the functionality builds on top of what was introduced in #112_

### Description

Continuing with the workspaces how-to guides 🕺🏼 

What's in this PR:
- Introduced a new workspaces category (and organized assets, docs, and sidebar accordingly)
- Wrote a new "Switching between workspaces" guide 
- Tweaked the original guides from #112 to reflect new functionality

Current generated-index for this category 👀 
<img width="1168" alt="Screenshot 2023-03-29 at 17 15 51" src="https://user-images.githubusercontent.com/26869552/228587022-57520ff8-613b-40bf-b4cd-42b60614ff4a.png">

### Additional Context

Internal Jira ticket 🎫 [CI-2036](https://emnify.atlassian.net/browse/CI-2036) ([parent task](https://emnify.atlassian.net/browse/CI-1907))

2023-04-03 07:35 UTC, techwriter-dev approved these changes

2023-04-04 06:19 UTC, jeffstahlnecker requested changes
I'm missing details on what roles can do what in this release of workspaces. Who can switch between different workspaces? Who can't? etc.

Bonus: It would be nice to prompt users to go to canny if a feature they expect to see in workspaces doesn't exist.

2023-04-24 09:23 UTC, carolstran commented
@jeffstahlnecker For the Canny prompt, would something like this at the end of each article work? 
<img width="866" alt="Screenshot 2023-04-24 at 11 22 44" src="https://user-images.githubusercontent.com/26869552/233955681-601307b1-f7b5-4d82-b0e9-553b04023a07.png">

2023-04-24 11:41 UTC, jeffstahlnecker approved these changes
Improved. Thanks!

2023-04-24 11:52 UTC, merged