Remove acronym descriptions from Glossary headers
emnify/product-docs pull request #116
Opened 2023-03-30 08:50 UTC by carolstran

### Description

Clean up based on a discussion with @techwriter-dev on Slack where he noted:

> In an older PR related to the Glossary you once asked in a conversation about whether or not to include the expanded meaning of acronyms in the section heading.
>
> I am against the current practice of including it for a couple of reasons:
> 1. Internal anchors are way too long: `[IMEI](#imei---international-mobile-equipment-identity)`
> 2. It clutters the view and makes a quick skimming of the text body (or page contents pane) more difficult.
>
> Also, I noticed that en-dashes (maybe even em-dashes?) are sometimes used as hyphens.

🧹 🧹 🧹 

<img width="767" alt="Screenshot 2023-03-30 at 10 46 02" src="https://user-images.githubusercontent.com/26869552/228782421-302cb6c8-3189-4927-b59b-e107e99e0435.png">

### Additional context

Internal ticket 🎫  [SDOCS-334](https://emnify.atlassian.net/browse/SDOCS-334)

[SDOCS-334]: https://emnify.atlassian.net/browse/SDOCS-334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-04-03 08:05 UTC, techwriter-dev requested changes
Added suggestions for fixing the broken links in `glossary.md`

Wasn't able to add a suggestion for line 167:
```

Following the introduction of [eUICC](#euicc---embedded-universal-integrated-circuit-card) SIM cards in 2021, there are situations where the ICCID can no longer be unique. 
```

2023-04-03 08:05 UTC, techwriter-dev commented on docs/glossary.md
>  A SIM stores data used to identify a subscriber ([IMSI](#imsi---international-mobile-subscriber-identity)) along with other network information for connecting and authenticating with a [mobile networ
```suggestion
A SIM stores data used to identify a subscriber ([IMSI](#imsi)) along with other network information for connecting and authenticating with a [mobile network operator (MNO)](https://www.emnify.com/iot-glossary/mno).
```

2023-04-03 08:05 UTC, techwriter-dev commented on docs/glossary.md
>  It allows consumers and IoT manufacturers to provision the SIM with a new [operator profile](https://www.emnify.com/iot-glossary/mno) [over-the-air](#ota---over–the–air).
```suggestion
It allows consumers and IoT manufacturers to provision the SIM with a new [operator profile](https://www.emnify.com/iot-glossary/mno) [over-the-air](#ota).
```

2023-04-17 09:58 UTC, carolstran commented
Excellent catch thank you so much @techwriter-dev 🙏🏼  updated and re-requested a review!

2023-04-19 20:02 UTC, carolstran commented
Applied all requested changes and overriding the merge permissions since John is on vacation this week 😇

2023-04-19 20:02 UTC, merged