Migrate current Python SDK documentation content
EMnify/product-docs pull request #12
Opened 2022-12-28 00:26 UTC by carolstran

Now that we know where our SDK content lives, let's add it to our migration 🐍 

💹 What's in this PR:
- Content from the current Python SDK (aka all of the [`rst` files in this directory](https://github.com/EMnify/emnify-sdk-python/tree/main/docs/sphinx))

⚠️ _**Warning: It's really just the current content. Almost no cleanup done to the language.**_ 

🙅🏼 What's _**not**_ included:
- Auto-generated API reference (separate ticket)
- SDK section overview page (also a separate ticket)

Internal ticket 🎟️  [SDOCS-72](https://emnify.atlassian.net/browse/SDOCS-72)

2023-01-06 08:40 UTC, techwriter-dev requested changes
Completed review.

2023-01-06 08:40 UTC, techwriter-dev commented on docs/sdks/python/concepts.md
> +| SMS  | [Learn more about SMS](https://www.emnify.com/developers/documentation#_sms).  |
Perhaps this should have been rebased prior to review so that the new internal link (`../services/sms`) could have been applied.

2023-01-06 08:40 UTC, techwriter-dev commented on docs/sdks/python/examples.md
> +## Device lifecycle management
Both [Merriam-Webster](https://www.merriam-webster.com/dictionary/life%20cycle) and [Cambridge Dictionary](https://dictionary.cambridge.org/dictionary/english/life-cycle?q=lifecycle) have only **life cycle** without any alternate orthography.

```suggestion
## Device life cycle management
```

2023-01-06 08:40 UTC, techwriter-dev commented on docs/sdks/python/examples.md
> +### Configure operator blocklist for device
Is this really supposed to be **blocklist** instead of **blacklist**?

The Python code below suggests **blacklist** is correct:

```python
emnify.devices.add_device_blacklist_operator(operator_id=all_operators[0].id, device_id=device_id)
```
```python
for operator in device_blacklist:
```

2023-01-06 08:40 UTC, techwriter-dev commented on docs/sdks/python/examples.md
> +You may want to refrain from using a specific operator to avoid unintentional spending on the device.
Is there a better way to say, "... spending on the device." ?

Maybe "... to avoid incurring costs with the device" or "... to avoid being billed for device usage."

2023-01-06 08:40 UTC, techwriter-dev commented on docs/sdks/python/examples.md
> +This is possible by adding the operator to the blocklist of the device:
Is this really supposed to be **blocklist** instead of **blacklist**?

The Python code below suggests **blacklist** is correct:

```python
emnify.devices.add_device_blacklist_operator(operator_id=all_operators[0].id, device_id=device_id)
```
```python
for operator in device_blacklist:
```

2023-01-06 10:39 UTC, carolstran commented on docs/sdks/python/examples.md
> +## Device lifecycle management
This would require a larger conversation, as all of the current emnify materials (both within [our docs platform](https://emnify.github.io/product-docs/services/events/event-types#data-connection-lifecycle) and [beyond](https://www.emnify.com/blog/sim-lifecycle-management)) use "lifecycle" (one word). If you search "SIM lifecycle" on Google as well, for instance, it seems to be an industry term.

That said, I believe "Device lifecycle management" should be changed to "Device status management" regardless as that was part of Viktoria's feedback for the [Events docs](https://emnify.github.io/product-docs/services/events/event-types#device-status-management). So I can update that here as well.

2023-01-06 10:41 UTC, carolstran commented on docs/sdks/python/examples.md
> +You may want to refrain from using a specific operator to avoid unintentional spending on the device.
Oh for sure, I just quickly updated the English from the original docs 🥴  I can improve for this iteration though!

2023-01-06 10:48 UTC, carolstran commented on docs/sdks/python/examples.md
> +This is possible by adding the operator to the blocklist of the device:
This is an interesting topic, as I know that emnify as an org is moving away from the term "blacklist" ([for obvious reasons](https://www.vice.com/en/article/v7dd3d/we-need-to-stop-saying-blacklist-and-whitelist)) towards "blocklist".

However, much of the underlying code still uses `blacklist` and this has also been an ongoing discussion with the Support team. In a previous conversation with Jorge, he referred to [this ticket](https://support.emnify.com/hc/en-us/articles/360020845139-How-to-block-operators-on-specific-devices-on-the-platform-) as an example of the confusion.

My thoughts were that we could take a similar approach to the company uses American English but API currently uses British debate - we write out in the new docs platform the terminology we are moving towards, then ensure that the technology will also be updated accordingly. 

What do you think?

2023-01-06 10:50 UTC, carolstran commented on docs/sdks/python/concepts.md
> +| SMS  | [Learn more about SMS](https://www.emnify.com/developers/documentation#_sms).  |
Oops you're totally right 🙈  Updating now!

2023-01-06 10:54 UTC, carolstran commented on docs/sdks/python/concepts.md
> +| SMS  | [Learn more about SMS](https://www.emnify.com/developers/documentation#_sms).  |
I also found a random leftover legacy docs link on the Events Type page, so if you see a random update there - that's why 😄

2023-01-06 10:56 UTC, carolstran commented on docs/sdks/python/examples.md
> +### Configure operator blocklist for device
Resolving here and [continuing the discussion here](https://github.com/EMnify/product-docs/pull/12/files#r1063333421)

2023-01-06 15:16 UTC, techwriter-dev commented on docs/sdks/python/examples.md
> +This is possible by adding the operator to the blocklist of the device:
Then we leave it as is.

I've just never encountered **blocklist**. Only **blockchain** and **blockhouse**.

2023-01-06 15:18 UTC, techwriter-dev approved these changes

2023-01-07 19:33 UTC, carolstran commented
@techwriter-dev Looks like something went wrong when you force pushed to this branch. I've updated it and it should be good to go now.

<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/26869552/211167424-690811bd-35f5-4224-8513-9282a41bb5a0.PNG" />
</details>

2023-01-07 19:33 UTC, merged