Update logo and top navigation
EMnify/product-docs pull request #13
Opened 2022-12-28 14:57 UTC by techwriter-dev

- Removed top navigation options
- Added new word-only logo and renamed the file to be more descriptive
- Replaced favicon with a light-mode emnify logo (blue on white background)

2023-01-01 20:35 UTC, techwriter-dev commented
@carolstran Is there anything else that needs to be done? Thanks!

2023-01-01 21:49 UTC, carolstran requested changes
Some details need updating before merging, but the styling looks great thank you ✨

2023-01-01 21:49 UTC, carolstran commented on docusaurus.config.js
> +        title: "Developer",
IMO this title should probably reflect the domain we choose, but either way this should be plural:

```suggestion
        title: "Developers",
```

2023-01-01 21:49 UTC, carolstran commented on docusaurus.config.js
> +          src: "img/logo-word-blue-295x80.png",
We should also add the logo for dark mode as part of this PR. 

Looking at the [Docusaurus docs](https://docusaurus.io/docs/api/themes/configuration#navbar-logo), we can use the `srcDark` field for this.

2023-01-01 21:49 UTC, carolstran commented on docusaurus.config.js
>            alt: "EMnify Logo",
It'd be great to add more descriptive alt text here:

```suggestion
          alt: "emnify Documentation – Home",
```

(could also be `Developer Documentation` or some other variation, up to you)

Reference: [Deque](https://www.deque.com/blog/great-alt-text-introduction/#:~:text=At%20a%20minimum%2C%20the%20alt,%E2%80%9CUser%20Testing%20%E2%80%93%20Home%E2%80%9D.)

2023-01-02 08:34 UTC, techwriter-dev commented on docusaurus.config.js
> +          src: "img/logo-word-blue-295x80.png",
Resolved in [commit 73a0a869](https://github.com/EMnify/product-docs/pull/13/commits/73a0a86995e8cb1a9c97a004b4df549f06ddc17e)

2023-01-02 08:48 UTC, carolstran approved these changes
Looks great, thank you 🎉

2023-01-02 10:01 UTC, merged