Publish initial draft of the emnify Portal user guide
emnify/product-docs pull request #142
Opened 2023-07-11 22:02 UTC by carolstran

### Description

🔜 🔮 🖥️ 📝  ✨ 👷🏼‍♀️ 

### Additional Context

2023-07-13 09:41 UTC, jeffstahlnecker requested changes
There are a few improvements that can be made before this is released. I did most of those by suggesting changes. There are a few things we should consider in future iterations: 

1. A lot of content looks like it duplicates content in the glossary. Is there a way to feed this from the glossary so we have one source of truth? Would an optimization like this make sense? 
2. There quite a bit of language here that can be simplified to make it easier to understand/read -- especially for non native speakers. I wouldn't block the initial launch, but it needs a good copy editor to go through it. I suggested a few changes, but I didn't provide all the content with that same level of attention. 
3. URL structure - should this be updated to match our evergreen approach as defined in the IA? Currently we have lots of embeds here vs keeping URLs top level so we can move pages in the future without changing the URLs.

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/dashboard.md
> +## Usage summary
What we're missing is how often the Dashboard is updated. This is a question that comes up quite often.

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/dashboard.md
> +**Devices Status**
What do these status's mean for the customer? Should that be linked or added here?

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/integrations/application-tokens.md
> +To add or view existing application tokens, navigate to [**Integrations**](https://portal.emnify.com/integrations) and scroll down to [**Application Tokens**](https://portal.emnify.com/integrations#a
```suggestion
To add or view existing [application tokens](https://docs.emnify.com/glossary#application-token), navigate to [**Integrations**](https://portal.emnify.com/integrations) and scroll down to [**Application Tokens**](https://portal.emnify.com/integrations#application-tokens).
```

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/integrations/application-tokens.md
> +1. Add a **Description** and optionally add an **Expiry date** or **IP restriction**.
We should add a notification or security information on why an expiration date or IP restriction is important.

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/integrations/no-code.md
> +For example, you can send a configuration SMS to set the proper APN when the device connects for the first time.
Would it make sense to link to our "How to" articles on Zapier as well as the video content we have instead of trying to explain the value here?

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/integrations/no-code.md
>  - Create a device (SIM configuration)
These look like actions and not triggers?

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/organization/billing.md
> +## Monthly cost details
How often is the current month updated? When will they see the usage they just did reflected in the billing? Would it makes sense to add this here?

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/organization/data.md
> +- Verification document type
Food for thought: this will be removed soon - currently blocked in CN.

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/organization/data.md
> +### Financial
Should we define which "role" these people have and what type of notifications they may get from us? For example if there's a billing problem, we'll talk to financial, if we find a problem with their system or notice an irregularity, our support will reach out to the technical contact etc.

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/organization/employees.md
> +Provide the employees's name, email address, and role.
```suggestion
Provide the employees's name, email address, and [role](https://docs.emnify.com/portal/user-management#user-management-1).
```

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/organization/sso.md
> +SSO provides several benefits, including improved network security and simplified administration.
```suggestion
SSO improves account security and simplifies user administration.
```

Network security can be understood as their cellular network, the network of devices -- so a bit unclear. If we can't list several additional benefits, we can be specific here to the two we are certain about.

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/organization/sso.md
> +Single sign-on (SSO) is only available with the [**Pro** plan](https://portal.emnify.com/organisation-settings/subscription).
```suggestion
Single sign-on (SSO) comes with the [**Pro** plan](https://portal.emnify.com/organisation-settings/subscription).
```

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/organization/workspaces.md
> +This feature is only available to [**Pro** plan](https://portal.emnify.com/organisation-settings/subscription) subscribers.
```suggestion
This feature comes with the [**Pro** plan](https://portal.emnify.com/organisation-settings/subscription) subscribers.
```

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/sims-and-devices/connected-devices.md
> +You can manage your devices from the [**Connected Devices**](https://portal.emnify.com/connected-devices) page.
```suggestion
 [**Connected Devices**](https://portal.emnify.com/connected-devices) is where you manage your devices.
```

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/sims-and-devices/connected-devices.md
> +### IMEI
This is a lot of glossary information. Is there any way to feed the data here from the glossary so there is one location to update it?

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/sims-and-devices/connected-devices.md
> +When you are ready to deploy a device and want it to connect to a network, change its status to **Enabled**.
```suggestion
When you want a device to connect to a network, change its status to **Enabled**.
```

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/sims-and-devices/connected-devices.md
> +To change a device's status, use the **Status** toggle from the **Connected Devices** list or the device's **Details** page.
```suggestion
To do this, use the **Status** toggle from the **Connected Devices** list or the device's **Details** page.
```
If the content is clearly connected with the previous sentence.

Were a lot of line breaks added to make the content stay on the left side of the page? If feels like we have a sentence per line...

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/sims-and-devices/connected-devices.md
> +Use a filter to display a list of the targeted devices.
This doesn't fit well together. The formatting makes it unclear that this paragraph is a "how-to"

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/sims-and-devices/device-policies.md
> +You can use [**Device Policies**](https://portal.emnify.com/device-policies) to create device groups to ease the management of large deployments.
It's better to describe this as a way to create unique coverage and network configurations that can then be assigned to devices. Calling device groups isn't entirely accurate.

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/sims-and-devices/device-policies.md
> +Choose device group policy names and device tags related to these criteria.
Service policy - these are not device groups.

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/sims-and-devices/device-policies.md
> +If you change a device's policy, be sure to [reset its connectivity](/portal/connected-devices#reset-connectivity) for the change to take effect.
A device policy - could be either a service policy or coverage policy. Should we be more explicit here?

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/sims-and-devices/device-policies.md
> +Develop a strategy for grouping your devices according to certain criteria related to your use cases, deployment regions, product lines, or services.
How does this tip interact with the tagging strategy? It's important that these features are used to manage network or coverage needs. Tags are better to use when configurations are the same, but something else is different.

2023-07-13 09:41 UTC, jeffstahlnecker commented on docs/portal/sims-and-devices/device-policies.md
> +### Update policies
Will updating a policy cause the devices in that policy to reset connectivity?

2023-07-13 09:55 UTC, carolstran commented on docs/portal/dashboard.md
> +pagination_next: portal/sims-and-devices/sim-inventory
The slug is on the next line, this is to determine which page appears in the `Next` pagination block and `portal/sims-and-devices/sim-inventory` is the internal id (determined by the repo structure) 😇

2023-07-13 10:03 UTC, carolstran commented on docs/portal/integrations/application-tokens.md
> +To add or view existing application tokens, navigate to [**Integrations**](https://portal.emnify.com/integrations) and scroll down to [**Application Tokens**](https://portal.emnify.com/integrations#a
When we're linking within the `docs.emnify.com` subdomain, we don't need the full url - only the slug (in this case, `/glossary#application-token`) 😁 

So I won't commit these changes but I'll locally update!

2023-07-13 10:09 UTC, carolstran commented on docs/portal/sims-and-devices/connected-devices.md
> +### IMEI
Would something like [what I did for the workspaces page](https://github.com/emnify/product-docs/pull/142/files#diff-7ba7fd7ae40ea47be164a2e3acf83f864d1c667cc84d6837084e62a77f34f711R14-R20) work? Then I can update the Glossary entries with any new data presented here.

2023-07-13 10:10 UTC, carolstran commented on docs/portal/sims-and-devices/connected-devices.md
> +To change a device's status, use the **Status** toggle from the **Connected Devices** list or the device's **Details** page.
I broke it up so it's easier to skim and find what you need, but I can have another look to make sure it makes sense in the context 👀

2023-07-13 10:55 UTC, carolstran commented on docs/portal/integrations/no-code.md
> +For example, you can send a configuration SMS to set the proper APN when the device connects for the first time.
These are legacy docs ([currently published here](https://docs.emnify.com/portal/no-code-automation)) so there's probably a decent amount that could be updated 😅 

There's a how-to is linked at the bottom but I can find others (if we have them) and move that up on the page. Would that work?

2023-07-13 11:12 UTC, carolstran commented on docs/portal/dashboard.md
> +**Inclusive Volume (per active device)**
Added this note! Let me know if Prepaid Balance should have its own section.

<img width="589" alt="Screenshot 2023-07-13 at 13 12 26" src="https://github.com/emnify/product-docs/assets/26869552/fb1c2e2a-1c79-45b0-a3c4-c294256bbc1b">

2023-07-13 11:15 UTC, carolstran commented on docs/portal/dashboard.md
> +For instance, if you selected **Europe Basic** as your *Main zone*, your first 100 MB (pooled across multiple devices) are free.
We don't really have a lot of documentation on what inclusive volume is... but I can link what we have and open a follow-up ticket for it?

2023-07-13 11:40 UTC, carolstran commented on docs/portal/integrations/application-tokens.md
> +1. Add a **Description** and optionally add an **Expiry date** or **IP restriction**.
This is what I wrote, let me know if it aligns with what you were thinking:

<img width="741" alt="Screenshot 2023-07-13 at 13 39 54" src="https://github.com/emnify/product-docs/assets/26869552/cbfe4a22-f5ef-4093-afcb-6c5e3733008e">

2023-07-13 11:49 UTC, carolstran commented on docs/portal/organization/billing.md
> +## Monthly cost details
Also asked, waiting for an answer 🫡

2023-07-13 12:15 UTC, carolstran commented on docs/portal/sims-and-devices/device-policies.md
> +Develop a strategy for grouping your devices according to certain criteria related to your use cases, deployment regions, product lines, or services.
I'm not sure... 🤔  Would it be ok to leave this tip in for the initial iteration and create a follow-up to re-evaluate? Or alternatively, I can delete for now then re-eval?

2023-07-13 12:17 UTC, carolstran commented on docs/portal/sims-and-devices/device-policies.md
> +### Update policies
From my understanding, based on the rest of this document, [you need to reset the connectivity](https://github.com/emnify/product-docs/pull/142/files#diff-f59ea62e3198187cf272de8b1413f1313ba06034a1d211177a46b678094e9e79R128-R129) to see changes (but the [changes are pushed](https://github.com/emnify/product-docs/pull/142/files#diff-f59ea62e3198187cf272de8b1413f1313ba06034a1d211177a46b678094e9e79R168) to the devices).

Do you know which team I can confirm this with?

2023-07-13 21:56 UTC, carolstran commented on docs/portal/organization/billing.md
> +## Monthly cost details
Added this based on some input from Kira, let me know if it should be more specific:

<img width="676" alt="Screenshot 2023-07-13 at 23 54 33" src="https://github.com/emnify/product-docs/assets/26869552/c63cc505-330e-40cc-add6-84c61db743c9">

2023-07-14 11:31 UTC, carolstran commented on docs/portal/sims-and-devices/device-policies.md
> +### Update policies
Alright heard from CN and updated accordingly:
<img width="912" alt="Screenshot 2023-07-14 at 13 22 18" src="https://github.com/emnify/product-docs/assets/26869552/d654d9ab-b09b-42c6-a483-219ca1897fdb">

2023-07-14 11:32 UTC, carolstran commented on docs/portal/dashboard.md
> +## Usage summary
Heard back and added an info block:
<img width="892" alt="Screenshot 2023-07-14 at 13 02 36" src="https://github.com/emnify/product-docs/assets/26869552/824e2474-425b-4c0d-b9d8-8a6b652de9eb">

2023-07-14 14:41 UTC, jeffstahlnecker approved these changes

2023-07-14 14:41 UTC, jeffstahlnecker commented on docs/portal/sims-and-devices/device-policies.md
> +## Assigning devices to a device group policy
What is a device group policy? We have service policies and coverage policies. We don't support a feature called "device groups."

2023-07-14 14:41 UTC, jeffstahlnecker commented on docs/portal/sims-and-devices/device-policies.md
> +Device group policies only become useful after you start assigning devices to them.
Service policies

2023-07-14 14:41 UTC, jeffstahlnecker commented on docs/portal/integrations/no-code.md
>  Using the Zapier webhook, you can also use triggers from:
You're missing

- Reconfigure a device
- Disable a device

2023-07-14 15:51 UTC, carolstran commented on docs/portal/dashboard.md
> +:::note
Ok I can make the note more explicit, thanks!

2023-07-14 15:59 UTC, carolstran commented on docs/portal/sims-and-devices/device-policies.md
> +## Assigning devices to a device group policy
Not sure where this wording came from, but didn't question it as this content was previously reviewed by Christian. I'll adjust though 🫡

2023-07-19 13:19 UTC, merged