Project redo
emnify/product-docs pull request #152
Opened 2023-07-28 15:47 UTC by eschkola

### Description

New structure and design of the python examples page.

### Additional Context

2023-07-28 17:58 UTC, carolstran requested changes
Left a few comments that focused on the formatting. I'll review the content in the next round.

General note: Your PR title should also be more descriptive. It's important for commit history as we squash PRs on merge and use the PR title as the commit message 😊

2023-07-28 17:58 UTC, carolstran commented on docs/sdks/python/examples-redo.md
> +slug: /sdks/python/examples
This will produce a duplicate route as `docs/sdks/python/examples.md` has the same slug value. We want to avoid this as it can lead to non-deterministic routing behavior.

I'd suggest adding your changes directly to `docs/sdks/python/examples.md` instead of creating a new file. That way, it's on the same route, it's easier to see what changed, and you wouldn't need to include the "Old overview" section at the bottom.

2023-07-28 17:58 UTC, carolstran commented on docs/sdks/python/examples-redo.md
> +| Manage device connectivity | To reset device's data connectivity or the network connectivity. <br> [Connectivity troubleshooting](https://www.emnify.com/developer-blog/5-ways-to-detect-and-solve-co
```suggestion
| Manage device connectivity | To reset device's data connectivity or the network connectivity. <br /> [Connectivity troubleshooting](https://www.emnify.com/developer-blog/5-ways-to-detect-and-solve-connectivity-issues#network-events) | [Source code](https://github.com/emnify/product-docs/blob/project-redo/docs/sdks/python/examples.md#manage-device-connectivity)  |
```

We're using Docusaurus, meaning all doc files are parsed using MDX. As a result, anything that looks like HTML is actually [JSX](https://docusaurus.io/docs/markdown-features/react#using-jsx-in-markdown), so we need to follow JSX conventions (in this case, closing tags for even for single-tag elements).

This is also what's causing the failing checks - once it's fixed, your build should go green!

2023-07-28 17:58 UTC, carolstran commented on docs/sdks/python/examples-redo.md
> +<summary>Alternative table</summary>
Because of the way the Markdown table is nested in the `details` element, this isn't rendering properly. That said, the first table you proposed is a good next step for this page so let's move forward with that and remove this one.

<details>
<summary>Screenshot of the alternative table while running locally</summary>
<img width="921" alt="Screenshot 2023-07-28 at 19 05 20" src="https://github.com/emnify/product-docs/assets/26869552/c9253426-86b1-48eb-aa51-0f28b275e979">
</detail>

2023-07-28 17:58 UTC, carolstran commented on docs/sdks/python/examples-redo.md
> +| Get your first device online     |   Follow these steps to get your devices online. The example demonstrates complex operations, such as: <ul><li>Device policies</li><li>SIM registration</li><li>De
When rendered, this table looks really nice! Thanks for adding the descriptions as well, I think it adds valuable context for our readers. 

A general formatting note - the source code links should go to the [examples in the emnify-python-sdk repo](https://github.com/emnify/emnify-sdk-python/tree/main/docs/examples). That way, the repo code acts as the single source of truth until we find a more programmatic way to pull these examples into the documentation.

For example:

```suggestion
| Get your first device online     |   Follow these steps to get your devices online. The example demonstrates complex operations, such as: <ul><li>Device policies</li><li>SIM registration</li><li>Device creation</li><li>SIM assignment</li><li>Error handling</li><li>Device details retrieval</li><li>Device activation or deactivation</li></ul>|  [Source code](https://github.com/emnify/emnify-sdk-python/blob/main/docs/examples/mass_sim_activation.py)  |
```

The [current Examples page](https://docs.emnify.com/sdks/python/examples) indicates which file the examples are from at the top of the code block:

<img width="486" alt="Screenshot 2023-07-28 at 19 28 50" src="https://github.com/emnify/product-docs/assets/26869552/a9f79545-c123-450f-9206-8c4e54138d14">

2023-07-31 08:09 UTC, eschkola commented on docs/sdks/python/examples-redo.md
> +| Manage device connectivity | To reset device's data connectivity or the network connectivity. <br> [Connectivity troubleshooting](https://www.emnify.com/developer-blog/5-ways-to-detect-and-solve-co
Oh I didn't know that! Thanks!!

2023-08-02 10:13 UTC, carolstran requested changes
This looks much better, and almost ready to merge! I added some comments and suggestions for ways to refactor. Once the table is re-formatted and the descriptions are uniform, then should be good to go ✨

2023-08-02 10:13 UTC, carolstran commented on docs/sdks/python/examples.md
> +| Get your first device online     |   Follow these steps to get your devices online. The example demonstrates complex operations, such as: <ul><li>Device policies</li><li>SIM registration</li><li>De
Looking at the description content, it'd be ideal if these were short, to the point, and start with a verb.

For example, this description could be something like:

```suggestion
| [Get your first device online](https://github.com/emnify/emnify-sdk-python/blob/main/docs/examples/mass_sim_activation.py)     |    Connect an emnify SIM to your device and configure the APN to access the internet. | 
```

Wrote this quickly so feel free to adjust based on the example! If you want me to suggest alternatives for the others as well, let me know.

2023-08-02 10:13 UTC, carolstran commented
Forgot to add this in my review notes, but thanks for updating the PR title and description 💖

2023-08-09 11:59 UTC, eschkola commented
Performed enhancements, happy to hear feedback about it! :)

2023-08-15 09:04 UTC, carolstran requested changes
Two of the examples are missing descriptions, but besides that mostly small tweaks this round 🔥

2023-08-15 09:04 UTC, carolstran commented on docs/sdks/python/examples.md
> +| [Manage device connectivity](https://github.com/emnify/emnify-sdk-python/blob/main/docs/examples/device_lifecycle_management.py#L143)  | Reset the device's or the network connectivity or check the
```suggestion
| [Manage device connectivity](https://github.com/emnify/emnify-sdk-python/blob/main/docs/examples/device_lifecycle_management.py)  | Reset the device or network connectivity and check the connectivity status. |
```

Unless you can think of a better way to weave the troubleshooting link into the description, I'd suggest removing it.

2023-08-15 09:08 UTC, carolstran commented on docs/sdks/python/examples.md
> +| [Filtering and sorting](https://github.com/emnify/emnify-sdk-python/blob/main/docs/examples/filtering_and_sorting.py) | Filter or sort lists of devices or SIM cards by passing several parameters.
Update: Opened the PR https://github.com/emnify/emnify-sdk-python/pull/220

2023-08-16 15:52 UTC, carolstran requested changes
The page looks great and I updated the branch to make sure the CI was working properly. Just need to fill in the two missing descriptions then this page is ready 💃🏼 🎉

2023-08-16 15:52 UTC, carolstran commented on docs/sdks/python/examples.md
> +| [Delete a device](https://github.com/emnify/emnify-sdk-python/blob/main/docs/examples/device_lifecycle_management.py)  |   |
My [original comment](https://github.com/emnify/product-docs/pull/152#discussion_r1294334492) might have gotten buried under the suggestion, but these two need a description ✍🏼

2023-09-04 13:40 UTC, carolstran approved these changes
Thanks for your effort (and patience) with this one, but I think it looks great now 🎉

2023-09-05 13:23 UTC, merged