Adapted Java quickstart to structure of Python quickstart
emnify/product-docs pull request #153
Opened 2023-07-31 15:15 UTC by eschkola

### Description

Adapted to structure from /product-docs/docs/sdks/python/quickstart.md

2023-08-02 11:16 UTC, carolstran requested changes
Great idea to make these pages more consistent, thanks for taking care! The page currently isn't rendering as expected, so I left some comments and suggestions to help. 

There were also some things I overlooked in a previous PR 🙈  so if you can help me fix those, that'd be great.

2023-08-02 11:16 UTC, carolstran commented on docs/sdks/java/quickstart.md
> +<b>Supported Java versions:</b>
We should use [Markdown formatting](https://www.markdownguide.org/basic-syntax/) wherever possible (this might also be why this section isn't rendering properly, see screenshot below).

If you want to keep it bold:

```suggestion
**Supported Java versions:**
```

Alternatively, we could turn this into an h4 (my preference):

```suggestion
#### Supported Java versions
```

<details><summary>Screenshot of Prerequisites section on current branch</summary>
<img width="730" alt="Screenshot 2023-08-02 at 12 56 14" src="https://github.com/emnify/product-docs/assets/26869552/c8aa4f9e-d880-4e43-9571-74972fdb6faf">
</details>

2023-08-02 11:16 UTC, carolstran commented on docs/sdks/java/quickstart.md
> +<!-- Alternative
This would be my choice, as lists tend to be easier for readers to scan and comprehend quickly. What do you think?

2023-08-02 11:16 UTC, carolstran commented on docs/sdks/java/quickstart.md
> +<b>TLS requirements: </b>
Same note as for "Supported Java versions" 😁

2023-08-02 11:16 UTC, carolstran commented on docs/sdks/java/quickstart.md
>  Replace *`VERSION_NUMBER`* with the version of Maven you're using.
```suggestion
Replace *`SDK_VERSION`* with the version of the emnify Java SDK you're using.
```

My mistake (see earlier comment) 🤪 If you could also update the placeholder in the code to say SDK_VERSION instead of VERSION_NUMBER, that'd be amazing 🙏🏼

2023-08-02 11:16 UTC, carolstran commented on docs/sdks/java/quickstart.md
>  Replace *`VERSION_NUMBER`* with the version of Gradle you're using.
```suggestion
Replace *`SDK_VERSION`* with the version of Gradle you're using.
```

Same comment and request as the Maven section 😇

2023-08-02 11:16 UTC, carolstran commented on docs/sdks/java/quickstart.md
> +To store configuration settings like an application token or a base URL, use environment variables instead of hardcoding them in your application. Here are some examples:
Why'd you decide reword this sentence? Asking because I think this wording is less clear than the original, but I might be missing context 🤔 

Either way, we want to keep each sentence in Markdown files on it's own line. That way, we can better see/track the diff.

```suggestion
To store configuration settings, like an application token or a base URL, use environment variables instead of hardcoding them in your application. 
Here are some examples:
```

2023-08-02 11:16 UTC, carolstran commented on docs/sdks/java/quickstart.md
> +If you're new to IoT connectivity and emnify, start by learning some [common terminology and concepts](/sdks/concepts) and explore some [use cases](/sdks/java/examples) that show what the SDK is capa
This is a big improvement, thank you 🙌🏼

2023-08-09 13:31 UTC, eschkola commented on docs/sdks/java/quickstart.md
> +To store configuration settings like an application token or a base URL, use environment variables instead of hardcoding them in your application. Here are some examples:
Ouh I didn't know that "one sentence - one line" thing. Good to know, thanks!

2023-08-09 13:33 UTC, eschkola commented on docs/sdks/java/quickstart.md
> +If you're new to IoT connectivity and emnify, start by learning some [common terminology and concepts](/sdks/concepts) and explore some [use cases](/sdks/java/examples) that show what the SDK is capa
Thanks!!

2023-08-09 13:34 UTC, eschkola commented
Fixed comments, happy to get feedback!

2023-08-15 09:31 UTC, carolstran approved these changes
Suggested some small tweaks that'd be great to apply before merging but overall looks good to go ✨

2023-08-15 09:31 UTC, carolstran commented on docs/sdks/java/quickstart.md
> +#### Supported Java versions:
Since we're going with headers, we don't need the colons.

```suggestion
#### Supported Java versions
```

2023-08-15 09:31 UTC, carolstran commented on docs/sdks/java/quickstart.md
> +[OpenJDK 8](https://openjdk.org/projects/jdk8/), [OpenJDK 11](https://openjdk.org/projects/jdk/11/), [OracleJDK 8](https://www.oracle.com/java/technologies/downloads/#java8) and [OracleJDK 11](https:
```suggestion

- [OpenJDK 8](https://openjdk.org/projects/jdk8/)
- [OpenJDK 11](https://openjdk.org/projects/jdk/11/)
- [OracleJDK 8](https://www.oracle.com/java/technologies/downloads/#java8)
- [OracleJDK 11](https://www.oracle.com/java/technologies/downloads/#java11)
```

Unless you have an argument against it, I'd prefer this stay in a list format 👩🏼‍🎨

2023-08-15 09:31 UTC, carolstran commented on docs/sdks/java/quickstart.md
> +#### TLS requirements:
```suggestion
#### TLS requirements

```

2023-08-16 13:58 UTC, eschkola commented
Fixed :)

2023-08-16 15:44 UTC, carolstran commented
@eschkola Updated your branch to make sure the CI is working properly now and everything is green ✅ 🍏 📗 🟢 💚  Feel free to merge!

2023-08-16 15:45 UTC, carolstran approved these changes

2023-08-16 15:46 UTC, carolstran commented
Also @eschkola FYI you don't need to re-request the review from me once it's approved (unless you added something new that you want me to check 😁 )

2023-08-24 12:18 UTC, merged