Migrate SIM registration guide from the Knowledge Base
emnify/product-docs pull request #165
Opened 2023-08-22 18:35 UTC by carolstran

### Description

🔗  [Original Knowledge Base article](https://support.emnify.com/hc/en-us/articles/360020090360-EMnify-quick-start-guide)

First part of the effort to refine and publish the REST API guides written by the CSM team 💃🏼 

### Additional Context

🎫  Part of [DOCS-113](https://emnify.atlassian.net/browse/DOCS-113)

2023-08-22 19:57 UTC, jeffstahlnecker requested changes

2023-08-22 19:57 UTC, jeffstahlnecker commented on docs/quickstart/register-sims.md
>  />
Image placement is odd. 
![Screenshot 2023-08-22 at 21 55 06](https://github.com/emnify/product-docs/assets/45363541/d32123ef-c63b-4b6c-8a6c-d357b1e4dc6b)

2023-08-23 09:35 UTC, carolstran commented on docs/quickstart/register-sims.md
>  />
Whoops my bad - fixed now! Although... we could also remove the image... 🔪 😂

2023-08-23 11:28 UTC, jeffstahlnecker approved these changes

2023-08-23 13:28 UTC, merged