Update documentation to use new pricing terminology
emnify/product-docs pull request #176
Opened 2023-08-30 21:27 UTC by carolstran

### Description

🤑 💸 🔜 📝 

### Additional Context

Internal 🎟️  [PGR-266](https://emnify.atlassian.net/browse/PGR-266)

2023-09-05 20:39 UTC, jeffstahlnecker requested changes

2023-09-05 20:39 UTC, jeffstahlnecker commented on docs/portal/sims-and-devices/device-policies.md
> +### Coverage
Review with Camila if she updated the policies page on this point.

2023-09-05 20:39 UTC, jeffstahlnecker commented on docs/quickstart/index.md
> +## emnify's Trial plan
```suggestion
## emnify's Trial
```

2023-09-05 20:39 UTC, jeffstahlnecker commented on docs/quickstart/index.md
> +After signing up, your account is automatically assigned to the **Trial plan**.
```suggestion
After signing up, your account is automatically assigned to the **Trial**.
```

2023-09-05 20:39 UTC, jeffstahlnecker commented on docs/quickstart/index.md
> +With the Trial plan, you have 60 days to use the issued prepaid credit for testing emnify's services.
```suggestion
With the Trial, you have 60 days to use the issued prepaid credit for testing emnify's services.
```

2023-09-05 20:39 UTC, jeffstahlnecker commented on docs/quickstart/index.md
> +Information on your current balance and other details about the Trial plan is available in the emnify Portal.
```suggestion
Information on your current balance and other details about the Trial is available in the emnify Portal.  
```

2023-09-05 20:39 UTC, jeffstahlnecker commented on docs/quickstart/index.md
> +In addition to the standard emnify services, the Trial plan supports the following features:
```suggestion
In addition to the standard emnify services, the Trial supports the following features:
```

2023-09-05 20:39 UTC, jeffstahlnecker commented on docs/quickstart/order-sims.md
> +For larger orders, you can split your order into **Batches** (for example, collections of 25, 100, or 500 SIMs).
```suggestion
For larger orders, you can split your order into **batches** (for example, collections of 25, 100, or 500 SIMs).
```

2023-09-05 20:39 UTC, jeffstahlnecker commented on docs/quickstart/troubleshooting.md
> +You can use the networks blocklist to block the network and force the change to a different network.
```suggestion
You can use the network blocklist to block the network and force the change to a different network.
```

2023-09-05 20:39 UTC, jeffstahlnecker commented on docs/support.md
> +**Starter Support** is included for all customers at no additional cost.
We should hold on the package name change.

2023-09-06 09:26 UTC, carolstran commented on docs/quickstart/index.md
> +After signing up, your account is automatically assigned to the **Trial plan**.
Anything that's bold reflects exactly how it's written in the Portal, so I'll confirm this before changing.

2023-09-06 09:27 UTC, carolstran commented on docs/quickstart/order-sims.md
> +For larger orders, you can split your order into **Batches** (for example, collections of 25, 100, or 500 SIMs).
This bolded term reflects what's written in the Portal, so I'll keep it as-is.

2023-09-06 09:40 UTC, carolstran commented on docs/support.md
> +**Starter Support** is included for all customers at no additional cost.
Ok I reverted the changes for the Support levels. If I should hold off on the general switch from **Standard Package** to **Starter Package**, let me know.

2023-09-06 09:44 UTC, carolstran commented on docs/portal/dashboard.md
> +This section is only shown if you're on the [Trial plan](/quickstart#emnifys-trial-plan).
Updated to "Trial" but still not sure what you mean by this comment... so if you give me more specifics, then I can update further.

2023-09-06 10:40 UTC, carolstran commented
@jeffstahlnecker FYI all of the updated events are from the MNO spec, so I'll update those docs and tag you in the PR.

2023-09-06 11:11 UTC, jeffstahlnecker approved these changes

2023-09-06 11:17 UTC, merged