Retructured portal device policies
emnify/product-docs pull request #190
Opened 2023-09-26 09:19 UTC by eschkola

### Description

Moved how-tos to separate folder. Restructured page and reword of content

### Additional Context

Link to ticket: [here](https://emnify.atlassian.net/browse/DOCS-91)

2023-09-26 16:17 UTC, eschkola commented
Images not found [here](https://github.com/emnify/product-docs/blob/redo-portal-device-policies/docs/portal/sims-and-devices/device-policies.md?plain=1#L83) in build command.
Carolyn notified.

2023-10-02 14:10 UTC, carolstran requested changes
Left some initial changes we need to tackle throughout this PR - once those are updated then we can go through and ensure the content makes sense in context. If you have any questions, let me know or we can discuss in our next call 😊

2023-10-02 14:10 UTC, carolstran commented on docs/portal/sims-and-devices/device-policies/how-to-assign-policy.md
> +---
General comment for all new pages: In most cases, every page should be accessible via the sidebar. Here's the Docusaurus docs on how to do that: https://docusaurus.io/docs/sidebar/items

As we discussed on Slack, that would also help me better understand how you expect the readers to move through the various pages and guides. If you have more questions about this, let me know and we can huddle.

2023-10-02 14:10 UTC, carolstran commented on docs/portal/sims-and-devices/device-policies.md
> +See this [guide for how to configure a webhook](/portal/device-policies/how-to-configure-webhook).
Not sure this section needs to be pulled into its own guide, as it covers how to use the tool (reference) rather than how to accomplish a specific goal (task). That said, I believe that we could add more context to this section to make it into a guide, but that would require substantially more work.

Let me know what you think, happy to reconsider!

2024-01-09 17:08 UTC, carolstran approved these changes

2024-01-09 17:08 UTC, merged