Update user documentation for MFA enforcement
emnify/product-docs pull request #210
Opened 2023-11-16 13:52 UTC by carolstran

### Description

Updated user documentation to provide clear and comprehensive guidance to users on how to set up and use MFA now that we'll start enforcing it January 2024.

### Updated slugs

Listed in order of change volume:

- `/how-tos/multi-factor-authentication`
- `/glossary`
- `/portal/user-settings`
- `/quickstart`
- `/how-tos`

### Additional Context

Internal 🎫 [CI-2605](https://emnify.atlassian.net/browse/CI-2605)

2023-11-16 14:02 UTC, jeffstahlnecker approved these changes

2023-11-16 14:15 UTC, martin-scholz-emnify requested changes

2023-11-16 14:15 UTC, martin-scholz-emnify commented on docs/how-tos/multi-factor-authentication.md
> +Once you've configured either method, you'll need to enter a one-time code to verify your identity if you log in to the Portal on a device you haven't [set as trusted](#manage-trusted-devices), use a
e-mail can't be configured so if you are enforced you are on e-mail mfa. Only if you configure TOTP you are on TOTP. 
Customers on eval can only be on TOTP as the are not forced. 
Enforcing is atm just for Enterprise customers of emnify.

2023-11-16 14:15 UTC, martin-scholz-emnify commented on docs/how-tos/multi-factor-authentication.md
> +These devices remain trusted for 30 days.
90 days

2023-11-17 13:37 UTC, carolstran commented on docs/how-tos/multi-factor-authentication.md
> +These devices remain trusted for 30 days.
I had a call with Lydia yesterday where she said it was going to be reduced to 30 days 🤔 but if the current system is 90 days, then I can put that in the docs now and then update again once it's reduced to 30 days. Wdyt?

2023-11-19 23:20 UTC, carolstran commented on docs/how-tos/multi-factor-authentication.md
> +These devices remain trusted for 30 days.
Confirmed that it'll be 30 days ✅

2023-11-28 08:56 UTC, merged