Clean up language and formatting on REST API page
EMnify/product-docs pull request #32
Opened 2023-01-09 06:46 UTC by carolstran

This page seems to have been migrated, but never updated to fit our existing scope. So this PR handles a quick clean up of the language and the Markdown formatting 🧼 

Internal ticket 🎟️  [SDOCS-149](https://emnify.atlassian.net/browse/SDOCS-149)

2023-01-09 08:54 UTC, techwriter-dev requested changes
A few minor corrections are needed.

2023-01-09 08:54 UTC, techwriter-dev commented on docs/rest-api.md
> +The sections below will describe the services available through the emnify API.
This is not wrong, but it's a practice I see many other writers using that doesn't provide the reader with any additional information.
Whenever I write, I ask myself, "Will removing this sentence deprive the reader of any essential information?"

For this reason, I avoid self-referencing constructions  like:
- The following sections ....
- In this guide / blog post / tutorial ...

IMO, the navigation and contents links are enough. This is standard REST API documentation without any surprises.

2023-01-09 08:54 UTC, techwriter-dev commented on docs/rest-api.md
> +As you should not store your emnify user credentials on your application server, you can generate an `application_token` via the [emnify Portal](https://portal.emnify.com/) or the API: `/api/v1/appli
This is a matter of personal taste. I can't recall any developer I ever worked with using **as** instead of **since** in this context.

```suggestion
Since you should not store your emnify user credentials on your application server, you can generate an `application_token` via the [emnify Portal](https://portal.emnify.com/) or the API: `/api/v1/application_token`.
```
An alternative would be:
```
We highly recommend that you never store your emnify user credentials on your application server.
You can generate an `application_token` via the [emnify Portal](https://portal.emnify.com/) or the API: `/api/v1/application_token`.

2023-01-09 08:54 UTC, techwriter-dev commented on docs/rest-api.md
> +This calls returns an `application_token`.
```suggestion
This call returns an `application_token`. 
```

2023-01-09 08:54 UTC, techwriter-dev commented on docs/rest-api.md
> +Unlike user and password authentication, only `auth_token`s are returned by the server.
Just to maintain consistency with line 96 (`user` vs `username`) and avoid the passive construction.
```suggestion
Unlike username and password authentication,  the server returns only `auth_token`s. 
```

2023-01-09 08:54 UTC, techwriter-dev commented on docs/rest-api.md
> +1. Send SMS to and endpoint: `POST /api/v1/endpoint/{endpoint_id}/sms`
```suggestion
1. Send SMS to an endpoint: `POST /api/v1/endpoint/{endpoint_id}/sms`
```

2023-01-09 08:54 UTC, techwriter-dev commented on docs/rest-api.md
> +Check out [JavaScript Examples](https://github.com/emnify/API_Examples_JS) with the emnify API in our GitHub repository.
This is a matter of preference. Since many of customers are not native speakers, it is probably better to avoid informal (slang) word choices like **check out**.

I would recommend **see**, **browse**, or **have a look at**.

The meaning here is "to have a look at", but when I consult dictionaries, "check out" in this context is more than simply looking at something. It actually implies _evaluating_ something:


**to go to a place in order to see what it is like:**
*I'm going to checkout that new club.*
-- _Cambridge Dictionary_ [check out](https://dictionary.cambridge.org/dictionary/english/check-out)

_Merriam-Webster_ doesn't even list an informal usage of [check out](https://www.merriam-webster.com/dictionary/check%20out).

2023-01-09 13:25 UTC, carolstran commented on docs/rest-api.md
> +Check out [JavaScript Examples](https://github.com/emnify/API_Examples_JS) with the emnify API in our GitHub repository.
That's a good point that I hadn't considered, thanks for sharing! 

This is also rollover content so I didn't write it and happy to change. In the future, I'll try to keep that in mind for my own writing but fair warning I say this _all the time_ so might need more reminders in the future 😅

2023-01-09 17:40 UTC, carolstran commented
@techwriter-dev I know we already closed this in Jira, but it'd be great to get your re-review and approval before merging 😇

2023-01-10 10:46 UTC, techwriter-dev requested changes
Just one suggestion to be applied.

2023-01-10 10:46 UTC, techwriter-dev commented on docs/rest-api.md
> +2. [**Authenticate with an application token**](#authenticate-with-an-application-token): You can use the application token generated in your emnify account.
@carolstran I thought for sure I had marked this one in my last review. I must have closed a tab by mistake.

```suggestion
1. [**Authenticate with an application token**](#authenticate-with-an-application-token): You can use the application token generated in your emnify account.
```

2023-01-10 15:11 UTC, carolstran commented
@techwriter-dev Updated!

2023-01-10 15:58 UTC, techwriter-dev approved these changes

2023-01-10 15:59 UTC, merged