Convert REST API page into category
EMnify/product-docs pull request #39
Opened 2023-01-10 23:09 UTC by carolstran

Inspired by #37, it makes more sense to have the link to the REST API reference in the main documentation sidebar so people can 1) know the content exists and 2) more easily access it. 

To enable this, I also converted the REST API page into the a category. The API reference link lives under this category.

Visual preview ✨ 
<img width="1271" alt="Screenshot 2023-01-10 at 17 04 57" src="https://user-images.githubusercontent.com/26869552/211681225-95afb6fc-b529-4f7b-9e61-05e9c37427af.png">

2023-01-11 14:25 UTC, techwriter-dev requested changes
The restructuring looks great.

Sorry that I got off scope with the English and formatting suggestions.

2023-01-11 14:25 UTC, techwriter-dev commented on docs/rest-api/authentication.md
>  1. [**Authenticate with user credentials**](#authenticate-with-user-credentials): Use the username and password you used while signing up for the [emnify Portal](https://portal.emnify.com/).
@carolstran I know this is not within the scope of your changes, but I was reading the content and found some English with repetitive word choices that could be changed to sound better. For instance, here we have **use*, **username**, **used** all in the same sentence. Perhaps:

> 1. [**Authenticate with user credentials**](#authenticate-with-user-credentials): Use the username and password you provided while signing up for the [emnify Portal](https://portal.emnify.com/).

2023-01-11 14:25 UTC, techwriter-dev commented on docs/rest-api/authentication.md
>  The request body should have a description of the token usually used to indicate who is using the token and can have an `expiry_date` for the token.
Another English word choice improvement regarding .**.. usually used ...**:
> ... should have a description of the token **normally** used to indicate who is using the token ...

On a side note, the value for `description` in the example below doesn't indicate "who is using the token":
```
"description": "Token with expiry date",
```

> ... and can have an `expiry_date` for the token.

Does this mean `description` is a **required** key in this JSON object and `expiry_date` is an **optional** key?
- **should** have a description
- **can** have an `expiry_date`

Also, why is `expiry_date` monospaced but `description` isn't?

2023-01-12 04:53 UTC, carolstran commented on docs/rest-api/authentication.md
>  The request body should have a description of the token usually used to indicate who is using the token and can have an `expiry_date` for the token.
Great questions - admittedly, I don't know the answers on hand. But I'd say this falls more into the scope of our future ticket to verify and update the content. Wdyt?

Either way, I swapped "usually" for "normally" 🫡

2023-01-13 08:51 UTC, techwriter-dev commented on docs/rest-api/authentication.md
>  The request body should have a description of the token usually used to indicate who is using the token and can have an `expiry_date` for the token.
I'm adding this to my list of content updates that will be needed that I'll add to the backlog.

2023-01-13 08:53 UTC, techwriter-dev approved these changes

2023-01-13 14:23 UTC, merged