SDOCS-60-Write-descriptive-README
emnify/product-docs pull request #41
Opened 2023-01-12 09:57 UTC by techwriter-dev

Created a minimal README with the updated requirements, mainly **Feedback and support**.

- Removed installation / getting started instructions
- Completed a short, streamlined **Contributing** section 

Internal ticket 🎫 [SDOCS-60](https://emnify.atlassian.net/browse/SDOCS-60)

2023-01-12 23:54 UTC, carolstran requested changes
We may have misaligned on the scope here... I left some comments, but overall, there are some structural components missing.

In this README, I would've expected there to be:
- ✅ Title and description (looks good!)
- Overview of the technologies used
- Pre-reqs and installation instructions (installation available in the original README)
- Local development and build instructions (available in the original README)
- Notes about deployment (mention we use GH actions, but we could also keep the information from the original README for manual deployment)
- ✅  Contributing guide (I left comments)
- Feedback and support (left a comment about this)
- License (I'm guessing we need this but good to check)

Resources:
- https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/
- https://www.makeareadme.com/
- https://github.com/kefranabg/readme-md-generator

2023-01-12 23:54 UTC, carolstran commented on README.md
> +For anything that might require an update or additional content, please [open a GitHub issue](https://github.com/emnify/product-docs/issues/new).
IMO this should be its own feedback or support section.

Also, for the `mailto` link, we can use standard Markdown:

```suggestion
If you have any suggestions, questions, or feedback, don't hesitate to [contact our documentation team](mailto:docs@emnify.com).
For anything that might require an update or additional content, please [open a GitHub issue](https://github.com/emnify/product-docs/issues/new).
```

2023-01-12 23:54 UTC, carolstran commented on README.md
> +Once you have signed a Contributor License Agreement (CLA), you can choose either of the following methods for contributing:
> Once you have signed a Contributor License Agreement (CLA)

AFAIK we don't have a CLA implemented. Were you planning to as part of this PR? 

Also, do we really need this? Might be worth syncing with Steffen if you haven't already.

2023-01-12 23:54 UTC, carolstran commented on README.md
> +    - Create a PR and submit it for review.
Can you tell me more about why you decided to structure it this way? I think I might be missing some context 🤔 

Typically, contributing sections might link to the GitHub workflow docs, but they don't explain the process of forking, branching, etc. step-by-step. 

For reference, these resources cover what I'd imagine would be included in a contributing section:
- https://mozillascience.github.io/working-open-workshop/contributing/
- https://contributing.md/how-to-build-contributing-md/

2023-01-12 23:54 UTC, carolstran commented on README.md
> +## Contributing
Looking at this PR, we might want to consider pulling this section content out into its own `CONTRIBUTING.md` file under the `.github` directory and linking to it from here. 

(not blocking, as we did agree to keep it simple to start - but could help keep our repo clean)

2023-01-13 12:10 UTC, techwriter-dev commented on README.md
> +    - Create a PR and submit it for review.
> Can you tell me more about why you decided to structure it this way? 

@carolstran Because that is [how **Microsoft** structures it](https://github.com/Azure/Azure-Sentinel#general-steps) for their external contributors:

2023-01-13 13:55 UTC, techwriter-dev commented on README.md
> +Once you have signed a Contributor License Agreement (CLA), you can choose either of the following methods for contributing:
@StephenKing I am hoping you can provide us with a direction to take regarding a Contributor License Agreement (CLA). Thanks!

2023-01-13 14:38 UTC, carolstran commented on README.md
> +    - Create a PR and submit it for review.
Microsoft doesn't make monolithic decisions like that, so we should be careful which documentation we're referencing as an example.

Regardless, let's keep it for now (especially as many people who might contribute aren't necessarily developers), but we should absolutely add back the steps for running locally, building, etc. as some contributors or teammates will need that.

2023-01-17 13:51 UTC, techwriter-dev commented on README.md
> +    - Create a PR and submit it for review.
I restructured it to be more logical.

The way Microsoft approached this with mixing one-time setup instructions with daily workflow was not logical.

2023-01-17 13:52 UTC, techwriter-dev commented on README.md
> +## Contributing
Let's discuss this later.

Maybe the TOC I added might make it more palatable.

2023-01-18 14:57 UTC, StephenKing commented
If I my share my opinion: why not move that into `CONTRIBUTING.md`, as it's IMHO the more natural place (and refer to it in the README). E.g. https://github.com/github/docs/blob/main/CONTRIBUTING.md

If I read through all of that, I'm probably closing the browser tab. Line endings? What? I think we easier get someone contributing when we lower the entry barrier. (I'm thinking here of some colleague or maybe even a customer)

Few thoughts on that:

- if we want a low-barrier entry, then directly editing in GitHub would be my default suggestion
- on MacOS, I think we don't need XCode. What about Homebrew?

2023-01-18 22:48 UTC, carolstran commented
> why not move that into `CONTRIBUTING.md`, as it's IMHO the more natural place (and refer to it in the README).
> 
> - if we want a low-barrier entry, then directly editing in GitHub would be my default suggestion
> - on MacOS, I think we don't need XCode. What about Homebrew?

Still planning to do a longer review tomorrow but fwiw I completely agree with these points from @StephenKing

2023-01-19 09:32 UTC, carolstran commented
@techwriter-dev As discussed in our call, I'll wait until you're done refactoring to review so just ping me when I should 👀

2023-01-25 16:03 UTC, carolstran requested changes
As always, let me know if you have any questions! Some of the suggestions can also be broken into separate tasks/PRs, so we can discuss 😁 

General question though - will the license be added as part of this PR or a separate one? My thinking is we could even throw in a MIT license for now to unblock the release and adjust later if needed 🚀

2023-01-25 16:03 UTC, carolstran commented on README.md
> +If so, please take a look at the [contributing guide](CONTRIBUTING.md) to see how easy it is to get started.
Same note about "easy" here 😊 

```suggestion
If so, please take a look at the [contributing guide](CONTRIBUTING.md) to see how to get started.
```

2023-01-25 23:09 UTC, techwriter-dev commented on CONTRIBUTING.md
> +```
@carolstran This was intended to be general information, not just for the initial installation.

Will they really never need to do a `git pull`?

2023-01-26 09:54 UTC, carolstran commented on CONTRIBUTING.md
> +```
Ah ok thanks for the context! I read it slightly differently at first, but let's keep it as-is then 😊

2023-01-27 09:57 UTC, carolstran commented on CONTRIBUTING.md
> +### GitHub will fork the repository for you
Just realized that anything related to forking is only relevant for external contributers - so we could consider cutting down that content, linking to the GitHub docs, and encouraging anyone internal to request access to the emnify GitHub org via Sharepoint if they haven't already 🕺🏼

2023-01-31 16:57 UTC, techwriter-dev commented on CONTRIBUTING.md
> +git config core.ignorecase false
Added to the changes I'm getting ready to push.

2023-02-06 22:55 UTC, carolstran requested changes
Overall, this guide is _so thorough_ and definitely walks someone new to GitHub through the workflow well. That said, this guide is very long and I'm worried it'll be a lot to maintain going forward. We could likely scale back some of the content and link to other related resources instead.

Left lots of comments 😬  but I tried to clearly label nits and the rest are open to discussion. Many of the comments are places where I'd suggest that we cut out the section or trim content.

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +Since we closely monitor the queue of PRs, it won't be long before a reviewer is assigned to your PR and has run the **Test deployment** script.
I'd be hesitant to promise this because even though I think it'll be the case, I want to manage expectations while we're still figuring things out 😅  

As an alternative, we can maybe add a link to the docs about tagging a reviewer 👀

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +If the reviewer supplied suggestions that can be applied, you can easily choose **Apply suggestion** directly through the UI.
Strong preference to avoid alienating terms like 'easily' or 'simple' in our docs 😁  

```suggestion
If the reviewer supplied suggestions that can be applied, you can choose **Apply suggestion** directly through the UI.
```

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +If there are several suggestions, they can be batched and applied all at once.
It also might help to add a link to [the relevant docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request) in this section

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +**It is important that you [resolve](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#resolving-conversations)
I'm wondering about cases where the people have questions or need us to respond or reply but would want us to resolve it... 🤔

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +1. Resubmit it for review.
We can cut this section as we can likely assume that people will know this workflow (or have their own)

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +Once all open conversations have been resolved, it is still possible that the reviewer might come across something else that needs to be changed, in which case the process will repeat itself again.
Another candidate for being cut as I don't think we need to explicitly say this

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +If the PR has made it to the stage of **Review**, typically it is only a matter of time before you will see your PR in the list of PRs with a status of **Approved**.
I wouldn't say this explicitly here as there are many reasons that we might not accept or merge a PR even after review

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +After it has been approved, it is likely to be merged without delay, in which case the changes will be publicly visible.
> it is likely to be merged without delay

Another phrase that, while probably right, I'd prefer we not explicitly say it because then we can manage expectations

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +- [Node.js](https://nodejs.org/en/download/): After installation, confirm that your Node.js version meets the [Docusaurus requirements](https://docusaurus.io/docs/installation#requirements).
Instead of linking to the Docusaurus requirements, we can explicitly say what version they need (esp since it needs to correspond with our project specifically)

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +- [yarn](https://classic.yarnpkg.com/en/docs/install)
Yarn should be uppercase (also needs to be updated throughout the doc)

```suggestion
- [Yarn](https://classic.yarnpkg.com/en/docs/install) 
```

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +**Note**: If you are an internal emnify contributor, you do not need to fork the repository.
We can probably cut this note because it's already mentioned earlier ✂️

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +**Note**: Internal emnify contributors should replace `yourUsername` with `EMnify`.
```suggestion
**Note**: Internal emnify contributors should replace `yourUsername` with `emnify`.
```

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +```
IMO this is something that might be better suited for the development guide because it's only really relevant if you're naming/renaming assets (unless I'm forgetting a use case)

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +However, you might need to run yarn occasionally  when new versions of your Node.js apps are released.
This section needs to be updated to better reflect Yarn's purpose as the package manager in our project. 

To help cut down content, we could also consider only saying that you use Yarn install the necessary dependencies for the project.

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +The default branch `main` is the public-facing version and doesn't contain your changes (yet)!
We may want to update this as technically the `gh-pages` branch is the public-facing version 🚀

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +These need to be explicitly checked out using Git.
If we're assuming the reader is new to using Git, then we could add the docs to checking out branches, etc here

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +You will need to use your terminal (or PowerShell), for starting your local Docusaurus server for previewing.
Genuine question: Do we need to specify PowerShell in this guide or would terminal be enough?

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +#### Frequently used git commands
Another option for cutting in favor of adding a link to the relevant docs ✂️

2023-02-06 22:55 UTC, carolstran commented on CONTRIBUTING.md
> +Any errors or warnings will be displayed both in the browser as well as in the terminal window.
> in the browser

If we're assuming the reader is new to web development, this could be too vague - we may want to be more specific about where these errors appear.

2023-02-07 11:14 UTC, carolstran commented
Shoot sorry forgot to add during my review, but it'd be super nice to add the link to the contributing guide in [our PR template](https://github.com/emnify/product-docs/blob/main/.github/PULL_REQUEST_TEMPLATE.md) 🙏🏼 ✨

2023-02-09 09:10 UTC, carolstran commented on CONTRIBUTING.md
> +## Creating new content
Just realized that we should probably add a subsection to this to describe how to add the new page to the sidebar since we aren't autogenerating it 👀

2023-03-14 23:05 UTC, carolstran requested changes
Overall, I still think that the contributing guide is very long and we likely don't need to explain the entire GitHub flow. But, as we're not sure who our primary contributors will be (if any), happy to experiment and see what feedback we get. 

Added some suggestions and nits. The most critical are that we need a license file and also figuring out a solution for contributors who do have GitHub experience.

2023-03-15 09:23 UTC, techwriter-dev commented on README.md
> +All documentation in this repository is licensed under the MIT license.
See [PR #105](https://github.com/emnify/product-docs/pull/105).

2023-03-16 17:24 UTC, carolstran requested changes
One comment to address and then I'd be ok with merging!

2023-03-16 17:24 UTC, carolstran commented on CONTRIBUTING.md
> +> If you prefer using developer tools for working with Git repositories, please see the [Developers](DEVELOPERS.md) guide.
Proposal: We should remove this and add it as part of #80 (or whatever PR ends up adding this type of guide) - that way, it isn't a blocker for merging this PR 🚀

2023-03-16 20:59 UTC, carolstran approved these changes

2023-03-16 21:03 UTC, merged