Quickstart: Removed references to eSIMs and scanning QR codes + Portal UI Updates
EMnify/product-docs pull request #50
Opened 2023-01-17 17:04 UTC by techwriter-dev

### Quickstart guide updates

- Removed references to eSIMs and scanning QR codes
- Added new images and updated the instructions to match the updated Portal UI elements.

Internal 🎫 [SDOCS-179](https://emnify.atlassian.net/browse/SDOCS-179)

2023-01-18 15:07 UTC, carolstran requested changes
Tried to leave specific comments, but let me know if anything is unclear.

@jeffstahlnecker also noted previously that the Registering SIMs page should likely be rewritten to use the SIM Inventory process instead of the Get started flow (as that disappears). That's out of scope for this PR though (as you're working with the existing content), but it'd be great to open a ticket to update this page.

2023-01-18 15:07 UTC, carolstran commented on docs/quickstart/registering-sims.md
> +  <img src={RegisterSIMs} style={{width:292}} alt="Register SIM(s)" />
Why are we setting a custom width on these images? 🤔 

Also, all images on this page would be considered decorative and should have an empty alt:
```suggestion
  <img src={RegisterSIMs} style={{width:292}} alt="" />
```

2023-01-25 22:17 UTC, techwriter-dev commented on docs/quickstart/registering-sims.md
> +import EnterBIC2 from './assets/portal-sim-registration-enter-bic2.png';
> @jeffstahlnecker also noted previously that the Registering SIMs page should likely be rewritten to use the SIM Inventory process instead of the Get started flow (as that disappears). That's out of scope for this PR though (as you're working with the existing content), but it'd be great to open a ticket to update this page.

Internal  🎫 [SDCOS-231](https://emnify.atlassian.net/browse/SDOCS-231)

2023-01-26 09:51 UTC, carolstran approved these changes
Huge improvement on the original pages, thank you 🥳

2023-01-26 09:51 UTC, carolstran commented on docs/quickstart/registering-sims.md
> +/>
Not blocking as its rendering well, but having each attribute on its own line helps make the code more readable 😊  

```suggestion
<img
  src={require('./assets/portal-get-started-collapsible-register-sims-menu-item.png').default}
  alt=""
  style={{ width: 292 }}
/>
```

2023-01-26 09:51 UTC, carolstran commented on docs/quickstart/registering-sims.md
> +If you order the free Evaluation SIM package, you will have to register each of the 3 SIMs separately.
Yay Bas mentioned removing "orange" from the original sentence here as a quick win and you already did that 👏🏼 🔪🧡

2023-01-30 08:41 UTC, merged