Replace old images with new branding
EMnify/product-docs pull request #51
Opened 2023-01-18 07:57 UTC by techwriter-dev

The goal is to replace all images that meet either of these 2 criteria

1. Screenshots that exhibit the **old branding**
1. Screenshots or diagrams that exhibit **problems with size, resolution, or scope of interest** (e.g., only a fraction of the screenshot is related to the topic of interest)

2023-01-23 08:59 UTC, techwriter-dev commented
Rebased `main` into this brach.

2023-01-23 13:42 UTC, carolstran requested changes
Tried to limit the number of comments and indicate when the feedback applied to multiple elements on a page, but if anything is unclear, please let me know!

Finally, I had two general comments:
- Do we want to standardize how we highlight specific areas of a screenshot? Right now we have circles of various colors, arrows, cropping, etc. 😅 
- Do we want to apply any of Aaron's feedback about distinguishing the images (e.g., through a background color, contour, or border)? 

These could both be handled in follow-up tickets, but I'd prefer we align before creating any 😇

2023-01-23 13:42 UTC, carolstran commented on docs/services/iot-cloud-communication-platform.md
> +import BreakoutRegions from './assets/portal-device-policies-breakout-regions.png';
IMO it could be more useful to expand this screenshot to show more of the new service policy setup (as it's a bit difficult to know which part of the Portal this is referring to).

Wdyt?

2023-01-23 13:42 UTC, carolstran commented on docs/services/iot-cloud-communication-platform.md
> +  <img src={BreakoutRegions} style={{width:889}} alt="Breakout regions" />
Regardless of what we do above, this will need a more descriptive alt text 😁 

I'll stop leaving individual comments for this, but it'd be worth double checking all of the alts in this PR.

2023-01-23 13:42 UTC, carolstran commented on docs/services/security.md
> +[emnify Portal](https://portal.emnify.com/) → **Device Policies** [emnify Portal](https://portal.emnify.com/) → **Device Policies** → **New service policy** → **More options**
Not sure if this is rendering as expected 🤔 

<img width="808" alt="Screenshot 2023-01-23 at 14 07 17" src="https://user-images.githubusercontent.com/26869552/214047319-85f6d4fd-725e-427c-a915-ae1a98c753d5.png">

2023-01-23 13:42 UTC, carolstran commented on docs/services/sms.md
> +import DetailsButton from './assets/portal-connected-devices-details-button.png';
We should crop this sidebar a bit more so the browser sidebar isn't showing

<img width="399" alt="Screenshot 2023-01-23 at 14 10 09" src="https://user-images.githubusercontent.com/26869552/214047904-7d35950c-a9c9-4e35-9299-2dbcab43a37b.png">

2023-01-23 13:42 UTC, carolstran commented on docs/services/sms.md
> +<img src={OpenSms} style={{width:350}} alt="" />
I would've expected this (and the following images) to be zoomable as well. Why'd you decide not to?

2023-01-23 13:42 UTC, carolstran commented on docs/services/sms.md
> +<img src={SmsConsole} style={{width:575}} alt="" />
We should crop out the visible sidebar if possible:

<img width="156" alt="Screenshot 2023-01-23 at 14 12 53" src="https://user-images.githubusercontent.com/26869552/214049174-388cdc43-72b0-40b3-9a32-3d937fdc4a61.png">

2023-01-23 13:42 UTC, carolstran commented on docs/services/sms.md
> +<img src={SmsMessage} style={{width:496}} alt="" />
Does this screenshot appear after you select devices and click SMS? This isn't completely clear for me 🤔

2023-01-23 13:42 UTC, carolstran commented on docs/services/sms.md
> +   <img src={DetailsButton} style={{width:1027}} alt="" />
IMO all of the screenshots on this page would be great contenders for proper alt text as they provide additional context that the text doesn't 💯

2023-01-23 13:42 UTC, carolstran commented on docs/services/sms.md
> +   <img src={SmsInterface} style={{width:800}} alt="" />
FYI this was exactly what I meant when commenting on `portal-device-policies-breakout-regions.png` 🙌🏼

2023-01-23 13:42 UTC, carolstran commented on docs/services/sms.md
>  Select Webhook and configure the URL and optionally, secret token to where you want the SMS to be delivered.
Should this text be distributed between the screenshots? Or was this layout intentional? If the latter, I'd love to learn more about that decision.

2023-01-23 13:42 UTC, carolstran commented on docs/services/sms.md
> +<img src={MoSms} style={{width:400}} alt="MO SMS" />
These two screenshots are a bit blurry... any chance we can increase the resolution on these?

2023-01-23 13:42 UTC, carolstran commented on docs/services/sms.md
>  *Mobile originated SMS from the device as received in Integromat webhook*
Are these meant to be captions? If yes, this isn't entirely clear based on the current layout.

Regardless, it's not a blocker for this PR - so we should just make sure to open a new ticket for this 🎟️

2023-01-23 13:42 UTC, carolstran commented on docs/services/sms.md
> +See also Zapier's [How to connect emnify + SMS by Zapier](https://zapier.com/apps/emnify/integrations/sms) guide.
Non-blocking idea, but this could make a nice admonition!

2023-01-24 10:27 UTC, carolstran commented on docs/quickstart/devices/android.md
> +import AndroidApnConfig from './assets/android-5-configure-apn.jpg';
Following up on this: As discussed in the refinement yesterday, lets leave this these elements as-is for now and refactor in [a future ticket](https://emnify.atlassian.net/browse/SDOCS-225) 😊

2023-01-24 10:34 UTC, carolstran commented on docs/quickstart/devices/android.md
> +  <img src={AndroidApnConfig} style={{width:200}} alt="" />
You mentioned on our call earlier that you'll remove these screenshots, so I'll resolve this conversation! I'll open a follow-up ticket for my last point though so we can look into it in the future.

2023-01-24 10:38 UTC, carolstran commented on docs/quickstart/devices/creating-a-device.md
> +import AddDevice from './assets/portal-connected-devices-add-device.png';
Discussed this on our call and leaving the scrollbar in was intentional, so I'll resolve this convo 🙈

2023-01-24 10:39 UTC, carolstran commented on docs/quickstart/devices/creating-a-device.md
> +  <img src={AddDevice} style={{width:1010}} alt="Connected Devices: Add Device" />
Alternative suggestion for moving forward - we could temporarily make all of the image alt texts blank (so its not a blocker for this PR) and then go through and add alt text in a future ticket 🤔 

If you'd prefer to do this, let me know and I'll add a follow-up task in Jira!

2023-01-24 10:45 UTC, carolstran commented on docs/quickstart/devices/ios-devices.md
> +import iOSapn from './assets/ios-4-apn.png';
This would be more of a nice-to-have than a blocker for merging, so I've [opened a follow-up ticket](https://emnify.atlassian.net/browse/SDOCS-227) and I'll resolve this convo 😊

2023-01-24 10:46 UTC, carolstran commented on docs/quickstart/getting-started.md
> +  <img src={EvaluationPack} style={{width:1031}} alt="FREE Evaluation SIM Package" />
I'd still be super curious about this (so that we can know how to move forward with image sizing in the future) but I'm resolving this conversation for now as it looks good and therefore, not blocking for the PR 😁

2023-01-24 10:47 UTC, carolstran commented on docs/services/iot-cloud-communication-platform.md
> +  <img src={BreakoutRegions} style={{width:889}} alt="Breakout regions" />
See my related suggestion here: https://github.com/EMnify/product-docs/pull/51#discussion_r1085099016

2023-01-24 10:47 UTC, carolstran commented on docs/services/sms.md
> +import DetailsButton from './assets/portal-connected-devices-details-button.png';
Not sure if this was an image where this as intentional (as discussed in our call earlier), but if yes then please resolve this convo!

2023-01-24 10:49 UTC, carolstran commented on docs/services/sms.md
> +<img src={SmsConsole} style={{width:575}} alt="" />
Not sure if this was an image where this as intentional (as discussed in our call earlier), but if yes then please resolve this convo!

2023-01-24 10:56 UTC, carolstran commented on docs/sso/microsoft-active-directory.md
> +![Upgrade to SSO](assets/portal-organization-no-sso-annotated.png)
Resolving this as it looks good and we can always crop more later 😊

2023-01-24 17:50 UTC, carolstran commented on docs/services/sms.md
>  *Mobile originated SMS from the device as received in Integromat webhook*
Wrote ticket: https://emnify.atlassian.net/browse/SDOCS-228

2023-01-24 18:13 UTC, carolstran commented
@techwriter-dev Pushed a couple of commits to address the changes we discussed and rebased with main. If everything looks ok for you, let me know then I'll approve the PR 🚀

2023-01-25 12:27 UTC, carolstran commented
@techwriter-dev Whoops sorry meant to ping you yesterday, but I pushed some commits to address the remaining comments! Please take a look and if everything seems ok for you, then I'll approve 🚀

2023-01-26 09:53 UTC, carolstran approved these changes
Approving since I'm the last one that touched this PR and don't want to be a blocker for it 🪨  

@techwriter-dev Let me know if there's anything else we should update or working before merging this! These images are going to make a big difference so thank you for taking the time on this one 👏🏼 🙏🏼 💖

2023-01-30 09:02 UTC, techwriter-dev commented
> Tried to limit the number of comments and indicate when the feedback applied to multiple elements on a page, but if anything is unclear, please let me know!
> 
> Finally, I had two general comments:
> 
> * Do we want to standardize how we highlight specific areas of a screenshot? Right now we have circles of various colors, arrows, cropping, etc. 😅

- I would prefer to use arrows as a primary means of annotating screenshots for indicating specific areas of interest.
- If a large area of the screenshot needs to be highlighted, then I like to enclosed the area in a red-bordered rectangle with rounded corners.

> * Do we want to apply any of Aaron's feedback about distinguishing the images (e.g., through a background color, contour, or border)?

Ideally, i would like to have images enclosed in a gray border (i.e., a standard palette name from those that Aaron shared closest to #808080) with 10px corner rounding and 12px thick. 

> 
> These could both be handled in follow-up tickets, but I'd prefer we align before creating any 😇

2023-01-30 09:05 UTC, techwriter-dev commented on docs/services/sms.md
> +<img src={MoSms} style={{width:400}} alt="MO SMS" />
No sure how to recreate these. These have been on the live site for a long time.

Perhaps decreasing the width would help? They are low res.

2023-01-30 09:36 UTC, carolstran commented
@techwriter-dev We have follow-up tickets for both of those ([colorful borders](https://emnify.atlassian.net/browse/SDOCS-242) and [screenshot annotations](https://emnify.atlassian.net/browse/SDOCS-245)) so lets discuss more in refinement 😁

2023-01-30 09:55 UTC, techwriter-dev commented on docs/services/sms.md
> +<img src={OpenSms} style={{width:350}} alt="" />
Standard markdown image syntax is zoomable by default due to the plugin.
For non-markdown syntax, if the text in an unzoomed image is just as readable as its zoomed version, then I have been not added the class.
For the sake of consistency, we could make all images zoomable, even icons, which I think is kind of odd.

2023-01-30 10:18 UTC, merged