Fix error in Teltonika GPS APN configuration command
EMnify/product-docs pull request #55
Opened 2023-01-19 21:55 UTC by carolstran

During our feedback session with Jorge, he mentioned that there's an error in the Teltonika GPS APN configuration setup command:

> the command is: Username (space) password (space)setparam 2001:em. If the devices do not have a username and password set, then it is the two leading spaces

So updated that and, as a bonus, I also cleaned up some of the grammar and formatting on this page 🧼 

✨ Visual preview

<details>
<summary>Currently published</summary>
<img width="724" alt="Screenshot 2023-01-19 at 21 43 31" src="https://user-images.githubusercontent.com/26869552/213566448-ca22b1e1-ca91-4815-b3e5-0eb39b6fa988.png">
</details>
</details>

<details>
<summary>After this PR</summary>
<img width="724" alt="Screenshot 2023-01-19 at 21 43 31" src="https://user-images.githubusercontent.com/26869552/213566179-77ea2371-ab5a-408e-a90d-38e6b30dfc3f.png">
</details>

2023-01-20 14:35 UTC, techwriter-dev requested changes
Provided a couple of suggestions.

2023-01-20 14:35 UTC, techwriter-dev commented on docs/quickstart/devices/gps-trackers.md
> +For some Concox models (e.g., TR02), the password needs to be sent with the command:
This might read better.
```suggestion
For some Concox models, for instance TR02, the password needs to be sent with the command:
```

2023-01-20 14:35 UTC, techwriter-dev commented on docs/quickstart/devices/gps-trackers.md
> +If it isn't set, you can omit the SMSpassword, and the command is:
The current construction with a compound sentence using "and" as the conjunction makes it sound like one is trying to maximize the suspense of the information that is about to be announced, e.g., " ... _and_ the winning (lottery) number is ....!" 

```suggestion
If the SMSpassword isn't set, the command is:
```
Also, we might want to investigate the orthography of "SMSpassword" given the way it is written on lines 155, 165, and 219.

2023-01-20 15:41 UTC, carolstran commented on docs/quickstart/devices/gps-trackers.md
> +If it isn't set, you can omit the SMSpassword, and the command is:
These were part of your original Quickstart PR, so my only goal here was to clean up some of the formatting that was missed 🤷🏼‍♀️  I'll commit your suggestions then it'll be ready for re-review!

2023-01-23 07:49 UTC, techwriter-dev requested changes
Only minor changes suggested.

2023-01-23 07:49 UTC, techwriter-dev commented on docs/quickstart/devices/gps-trackers.md
> +For GPS vendors that aren't listed, please consult the respective manual and configure the APN to be `em` or `emnify`.
```suggestion
For GPS vendors that aren't listed, please consult their respective manual and configure the APN to be `em` or `emnify`.
```

2023-01-23 07:49 UTC, techwriter-dev commented on docs/quickstart/devices/gps-trackers.md
> +Configuring the APN for Ruptela GPS trackers can be done through:
I'm not sure I why I didn't notice this earlier. 

We should either strike **through** or **Via** because both cannot be read together without it sounding wrong.

Configuring the APN for Ruptela GPS trackers can be done through: 

1. The SMS console of the [emnify Portal](https://portal.emnify.com/)

Also, note the change in the 2nd enumerated item above.

2023-01-23 08:41 UTC, carolstran commented on docs/quickstart/devices/gps-trackers.md
> +Configuring the APN for Ruptela GPS trackers can be done through:
Great points! These should definitely be considered when we verify and update the content for these pages (maybe you can add a comment to that ticket).

2023-01-23 08:56 UTC, carolstran commented
@techwriter-dev Changes applied, please re-review 😁

2023-01-24 07:10 UTC, techwriter-dev approved these changes

2023-01-24 07:57 UTC, merged