Fix links to broken pages
EMnify/product-docs pull request #57
Opened 2023-01-20 09:46 UTC by carolstran

Fixed all of the broken links flagged by João's feedback email, plus updated other glossary links so they aren't relative (and therefore, more likely to break in the future) 🚀

2023-01-20 14:54 UTC, techwriter-dev requested changes
2 suggestions need to applied that are related to a single internal link.

2023-01-20 14:54 UTC, techwriter-dev commented on docs/services/security.md
> +Secure Access Service Edge ([SASE](/glossary#sase-secure-access-service-edge)) introduces a new architecture where networking and security functions are bundled in a cloud-delivered service.
```suggestion
Secure Access Service Edge ([SASE](/glossary#sase---secure-access-service-edge)) introduces a new architecture where networking and security functions are bundled in a cloud-delivered service.
```

2023-01-20 14:54 UTC, techwriter-dev commented on docs/services/security.md
> +Some of the features that [SASE](/glossary#sase-secure-access-service-edge) for IoT architecture includes are as follows:
```suggestion
Some of the features that [SASE](/glossary#sase---secure-access-service-edge) for IoT architecture includes are as follows:
```

2023-01-20 15:34 UTC, carolstran commented on docs/services/security.md
> +Some of the features that [SASE](/glossary#sase-secure-access-service-edge) for IoT architecture includes are as follows:
Ah great catches, thank you! I'll make sure the other glossary links are also up-to-date as I updated some of the headers in a previous PR.

2023-01-20 15:38 UTC, carolstran commented
@techwriter-dev Checked the other glossary links as well and they seem good, so this should be ready for re-review 👀

2023-01-23 07:50 UTC, techwriter-dev approved these changes

2023-01-23 08:38 UTC, merged