Add initial Java SDK documentation
EMnify/product-docs pull request #75
Opened 2023-02-01 19:15 UTC by carolstran

### Description

The Python SDK docs looked lonely, so added some initial Java SDK docs based on what was available in the [GitHub repo](https://github.com/EMnify/emnify-sdk-java) 👯

2023-02-02 14:20 UTC, techwriter-dev requested changes

2023-02-02 14:20 UTC, techwriter-dev commented on sidebars.js
> +              "The emnify Java software development kit (SDK) for SIM state management and device connectivity operations.",
This should be the same as what we did with **Quickstart** on line 14 above.

It's functioning as a _subtitle_, not as a description.

![java-sdk-subtitle](https://user-images.githubusercontent.com/49970529/216347459-e7e4a278-c557-48e0-b438-6ba59b899449.png)

2023-02-02 14:20 UTC, techwriter-dev commented on docs/sdks/java/getting-started.md
> +| `EMNIFY_APPLICATION_TOKEN`  | Variable for authentication via [application token](https://cdn.emnify.net/api/doc/application-token.html). |
```suggestion
| `EMNIFY_APPLICATION_TOKEN`  | Variable for authenticating via an [application token](https://cdn.emnify.net/api/doc/application-token.html). |
```

2023-02-02 14:20 UTC, techwriter-dev commented on docs/sdks/java/getting-started.md
> +| `EMNIFY_USERNAME` and `EMNIFY_PASSWORD` | Variable for authentication via [username and password](https://cdn.emnify.net/api/doc/basic-auth.html). |
```suggestion
| `EMNIFY_USERNAME` and `EMNIFY_PASSWORD` | Variables for authenticating via [username and password](https://cdn.emnify.net/api/doc/basic-auth.html). |
```

2023-02-02 14:20 UTC, techwriter-dev commented on docs/sdks/java/getting-started.md
> +If you're new to IoT connectivity and emnify, start by learning the [common terminology and concepts](../concepts).
```suggestion
If you're new to IoT connectivity and emnify, start by learning some [common terminology and concepts](../concepts). 
```

2023-02-02 14:20 UTC, techwriter-dev commented on docs/sdks/java/help.md
> +- If you've found a bug in the library or would like to add new features, go ahead and [open issues or pull requests to our Github repository](https://github.com/emnify/emnify-sdk-java).
```suggestion
- If you find a bug in the library or would like to add new features, go ahead and [open issues or pull requests in our GitHub repository](https://github.com/emnify/emnify-sdk-java).
```

2023-02-02 17:08 UTC, carolstran commented on docs/sdks/java/getting-started.md
> +The emnify Java SDK is open source and the [source code is available on GitHub](https://github.com/EMnify/emnify-sdk-java).
I've more commonly seen it referred to by popular projects and companies as two separate words without a hyphen (see: [Google Open Source's style guide](https://opensource.google/documentation/reference/comms/style-guide#quick_reference)). This has also been true for previous open source projects I've worked on. We're also using American English, so we should probably be using American companies/projects/publications as our reference.

That said, we agreed on using the AP style guide as a fallback for these discussions and they recommend hyphenating when a two-word phase form an adjective - so I will update it 😊

2023-02-02 17:10 UTC, carolstran commented on docs/sdks/java/getting-started.md
> +You can use environment variables for storing configuration like application token or base URL rather than hardcoding them into your application.
Thanks for catching this, I must've missed it during my migration and quick cleanup. I'll update!

2023-02-02 17:21 UTC, carolstran commented
@techwriter-dev Ready for re-review!

2023-02-03 07:25 UTC, techwriter-dev approved these changes

2023-02-03 07:26 UTC, techwriter-dev commented on docs/sdks/java/getting-started.md
> +You can use environment variables for storing configuration like application token or base URL rather than hardcoding them into your application.
This has been resolved according to the latest commit.

2023-02-03 09:19 UTC, merged