Add troubleshooting toggle for phone number verification issues in Quickstart
emnify/product-docs pull request #77
Opened 2023-02-02 17:26 UTC by carolstran

ℹ️  _Marked as Blocked because the updated error messages aren't on prod yet_

### Description

Growth squad is updating error messages to help users better understand what's happening when their phone number is unable to be verified when signing up for the Portal. 

To help ease potential frustration, I thought it'd be nice to add a troubleshooting toggle in our Quickstart documentation to show common error messages and tips for getting around them.

### ✨ Visual preview

⚠️ **This details element has the same styling issues as the ones solved in #40** ⚠️ 
_This means that it'll look wonky until it's deployed_ 🥴

<img width="561" alt="Screenshot 2023-02-02 at 16 37 20" src="https://user-images.githubusercontent.com/26869552/216374853-cbd5567f-8ec3-46d1-b926-268b9d948fbb.png">

<details>
<summary>Expanded view (keeping in mind the note above)</summary>
<img width="789" alt="Screenshot 2023-02-02 at 16 37 01" src="https://user-images.githubusercontent.com/26869552/216375043-52e2f951-b544-4afe-83dd-22d67df00cbe.png">
</details>

In the end, the colors/design will match the caution admonition:

<details>
<summary> Example from the Events docs</summary>
<img width="589" alt="Screenshot 2023-02-02 at 16 44 12" src="https://user-images.githubusercontent.com/26869552/216375535-472f3766-21fa-469c-9117-c2d23bd6ad19.png">
</details>

### Additional Context

Internal ticket 🎟️ [PGR-153](https://emnify.atlassian.net/browse/PGR-153)

2023-02-03 08:39 UTC, carolstran commented
Feedback from Bas:

> Those options are already better. In case of a separate troubleshooting page, you can always add a link that goes to the that page with an anchor to the sign up part

I'll refactor accordingly! My first instinct is to use the blue 'info' color and change the text to `Need help verifying your phone number?`. We could also consider moving this information to the troubleshooting page, but my worry with that is that this page is so focused on connectivity now and someone wouldn't think to look there if they are having issues signing up 🤔

2023-02-03 10:45 UTC, carolstran commented
@techwriter-dev This is ready for your review now 😊

2023-02-03 16:09 UTC, techwriter-dev requested changes
@carolstran This looks absolutely amazing! 🎉

The only thing I would change is the punctuation for the bulleted items.

Since they are all complete sentences, I would terminate them with a period.

2023-02-06 09:59 UTC, techwriter-dev approved these changes

2023-02-06 15:57 UTC, merged