Migrate the Quickstart guide
EMnify/product-docs pull request #8
Opened 2022-12-23 10:36 UTC by techwriter-dev

Migrated the Quickstart section from a single section in the original .adoc into separate .md files within a new file and directory structure that  closely reflects its original content outline:

```
quickstart
├── assets
│   ├── attached.png
│   ├── offline.png
│   ├── online.png
│   └── reset_connectivity.png
├── devices
│   ├── android.md
│   ├── assets
│   │   └── placeholder
│   ├── cellular-modules.md
│   ├── creating-a-device.md
│   ├── getting-the-first-device-online.md
│   ├── gps-trackers.md
│   ├── industrial-routers.md
│   └── ios-devices.md
├── index.md
├── order-a-sim-package.md
├── quickstart.md.monolithic
├── registering-sims.md
└── troubleshooting.md
```

2022-12-23 21:09 UTC, techwriter-dev commented on docs/integration/amazon-web-services.md
> +# Amazon Web Services
Resolved with commit [85e4881](https://github.com/EMnify/product-docs/pull/8/commits/85e48812d8a4828ecf8f121d4854e9f8e7704fe2)

2022-12-23 21:14 UTC, techwriter-dev commented on docs/quickstart/devices/assets/placeholder
> +Since Git tracks only files, not directories, this file
Resolved with commit [dc9c00d](https://github.com/EMnify/product-docs/pull/8/commits/dc9c00dc6bf946521b7373a19477d89239d5eaa3)

2022-12-23 21:15 UTC, techwriter-dev commented on docs/quickstart/index.md
> +# Quickstart
Resolved by applying asuggestion.

2022-12-23 21:35 UTC, techwriter-dev commented on docs/quickstart/index.md
> +[Sign up](https://portal.emnify.com/sign/up?utm_source=dev-hub) for free to a 60-day trial to use all functionalities.
Resolved with commit [b0af681](https://github.com/EMnify/product-docs/pull/8/commits/b0af681e877e113a0a54a8c6301d24ed190eb730)

2022-12-23 22:12 UTC, techwriter-dev commented on sidebars.js
> +        },
Resolved in commit [60e0707](https://github.com/EMnify/product-docs/pull/8/commits/60e0707320d3e5e15b67cf66f5e95b609eaf27d4)

2022-12-23 22:12 UTC, techwriter-dev commented on sidebars.js
>      },
Resolved in commit [60e0707](https://github.com/EMnify/product-docs/pull/8/commits/60e0707320d3e5e15b67cf66f5e95b609eaf27d4)

2022-12-23 22:13 UTC, techwriter-dev commented on docs/quickstart/index.md
> +# Quickstart
Somehow this was not resolved completely by the suggestion.
Finally resolved in commit [60e0707](https://github.com/EMnify/product-docs/pull/8/commits/60e0707320d3e5e15b67cf66f5e95b609eaf27d4)

2022-12-28 15:00 UTC, techwriter-dev commented on docusaurus.config.js
>          },
@carolstran This was out-of-scope by default since the PR branch was created from a cherry-pick that included the filesystem changes needed to avoid duplicate work in this PR.

These design/style changes will be tracked in [PR #13](https://github.com/EMnify/product-docs/pull/13)

2022-12-29 09:24 UTC, techwriter-dev commented on src/css/custom.css
> +  --ifm-color-primary: #007e83;
@carolstran This was out-of-scope by default since the PR branch was created from a cherry-pick that included the filesystem changes needed to avoid duplicate work in this PR.

These design/style changes will be tracked in https://github.com/EMnify/product-docs/pull/13

2022-12-29 09:26 UTC, techwriter-dev commented on docusaurus.config.js
> +          src: "img/logo.png",
@carolstran This was out-of-scope by default since the PR branch was created from a cherry-pick that included the filesystem changes needed to avoid duplicate work in this PR.

The changes you proposed here (resizing and filename change) have already been completed in the following PR.

These design/style changes will be tracked in https://github.com/EMnify/product-docs/pull/13

2022-12-29 09:29 UTC, techwriter-dev commented
@carolstran I think I addressed all the discussions. Would you like to have another look before I merge.

As you can see above, GitHub is requesting that I resolve the merge conflict(s) via CLI.
I'm assuming that means locally.

Thanks!

2023-01-02 15:51 UTC, techwriter-dev commented on docs/quickstart/registering-sims.md
> +Login to your [emnify account](https://portal.emnify.com?utm_source=dev-hub).
Thanks! I'm surprised I didn't catch that one.

2023-01-02 17:35 UTC, techwriter-dev commented on docs/quickstart/troubleshooting.md
> +![offline.png](assets/offline.png) **The device is offline**
Resolved in [commit e3621b9](https://github.com/EMnify/product-docs/pull/8/commits/e3621b95cff112dc4a17bff239de89b1fd79d663).

2023-01-02 17:35 UTC, techwriter-dev commented on docs/quickstart/troubleshooting.md
> +- Clicking reset connectivity![reset\_connectivity.png](assets/reset_connectivity.png)on Connected Devices can also reset the network state and allow your device to freshly reattach.
Resolved in [commit e3621b9](https://github.com/EMnify/product-docs/pull/8/commits/e3621b95cff112dc4a17bff239de89b1fd79d663).

2023-01-02 17:36 UTC, techwriter-dev commented on docusaurus.config.js
> +  url: "https://docs.emnify.com",
I think this has been resolved by another PR.

2023-01-02 17:36 UTC, techwriter-dev commented on docusaurus.config.js
>    tagline: "Solutions for your deployments",
I think this has been resolved by another PR.

2023-01-02 17:42 UTC, techwriter-dev commented on docusaurus.config.js
> +          //  "https://github.com/emnify/product-docs",
@carolstran I made a note to open a Jira ticket for this since this is not within the scope of this issue.

2023-01-02 17:43 UTC, techwriter-dev commented on docusaurus.config.js
> +          //  "https://github.com/emnify/product-docs",
@carolstran I made a note to open a Jira ticket for this since this is not within the scope of this issue.

2023-01-02 17:45 UTC, techwriter-dev commented on docs/quickstart/troubleshooting.md
> +## Other general troubleshooting tips
Resolved in [commit e3621b9](https://github.com/EMnify/product-docs/pull/8/commits/e3621b95cff112dc4a17bff239de89b1fd79d663).

2023-01-02 17:46 UTC, techwriter-dev commented on docs/rest-api/index.md
> +# REST API
@carolstran I think this has been resolved in another PR.

2023-01-02 17:47 UTC, techwriter-dev commented
@carolstran I made extensive changes in [commit e3621b9](https://github.com/EMnify/product-docs/pull/8/commits/e3621b95cff112dc4a17bff239de89b1fd79d663) to resolve the discussions within the scope of this issue.

2023-01-02 17:52 UTC, carolstran commented on docs/rest-api/index.md
> +# REST API
Can you send a link to the PR that resolves this please? I don't see any that update these sections 🤔  

Either way, nothing that says "Coming soon!" should be merged into `main` so these pages would need to be removed.

2023-01-02 17:57 UTC, carolstran commented on src/css/custom.css
> +  --ifm-color-primary: #007e83;
If we both agree this is out of scope, then I'd suggest rebasing against the current `main` and not be updating any of the values in this PR. Wdyt?

2023-01-02 18:07 UTC, techwriter-dev commented
@carolstran Merged main into this branch and resolved the conflicts.

2023-01-02 18:20 UTC, carolstran requested changes
Tried to leave specific comments, but there are still some placeholder docs or lines in the sidebar config that need to be removed (including the logo file, which I couldn't comment on directly) 🔥

2023-01-02 18:20 UTC, carolstran commented on sidebars.js
> +        },
This causes errors when trying to build the branch locally since these files aren't available, so they need to be removed.

<img width="977" alt="Screenshot 2023-01-02 at 19 02 37" src="https://user-images.githubusercontent.com/26869552/210265842-3667c572-e706-49d3-ad62-2a3832ce7fc5.png">

2023-01-02 18:20 UTC, carolstran commented on sidebars.js
> +      // link: {type: 'doc', id: 'integration/'},
IMO this line should be removed completely rather than commented out (then we can re-add when we migrate the Integration guides)

2023-01-02 18:20 UTC, carolstran commented on sidebars.js
> +        type: 'generated-index',
Currently the generated-index is pulling the first sentences from each doc as the preview. You'll want to add a `description` to the front matter in each doc to write a more descriptive preview.

<img width="935" alt="Screenshot 2023-01-02 at 19 14 05" src="https://user-images.githubusercontent.com/26869552/210266814-6f72530e-02b6-445c-b480-7b30bb2fd6f1.png">

2023-01-02 18:20 UTC, carolstran commented on sidebars.js
> +        'quickstart/order-a-sim-package',
This needs to be expanded into an object so we can make the link sidebar title case (to be consistent with the others)

2023-01-03 07:25 UTC, techwriter-dev commented on sidebars.js
> +        },
Added untracked Devices md files to Git [7ec13af](https://github.com/EMnify/product-docs/pull/8/commits/7ec13af00957af39b54dde9b7eca10bb44f23c75).

2023-01-03 09:15 UTC, techwriter-dev commented on docs/rest-api/index.md
> +# REST API
Resolved in commit [76e559a](https://github.com/EMnify/product-docs/pull/8/commits/76e559a922afeb6b8347e35cdefbc98769a319b2).

2023-01-03 09:16 UTC, techwriter-dev commented on sidebars.js
> +      // link: {type: 'doc', id: 'integration/'},
Resolved in commit [76e559a](https://github.com/EMnify/product-docs/pull/8/commits/76e559a922afeb6b8347e35cdefbc98769a319b2).

2023-01-03 09:17 UTC, techwriter-dev commented on sidebars.js
> +        type: 'generated-index',
Resolved in commit [41876ca](https://github.com/EMnify/product-docs/pull/8/commits/41876cad57fd5dac0ac024a66556ec7eef476499).

2023-01-03 09:27 UTC, techwriter-dev commented on src/css/custom.css
> +  --ifm-color-primary: #007e83;
Resolved in commit [96efd23](https://github.com/EMnify/product-docs/pull/8/commits/96efd23460395649b49dfc26c8248c30dc9fb1fa).

2023-01-03 09:30 UTC, techwriter-dev commented on sidebars.js
> +        'quickstart/order-a-sim-package',
@carolstran I believe this is resolved in one of the 4 commits I pushed this morning.

I checked to make sure everything was in title case.

2023-01-03 16:42 UTC, carolstran requested changes
I was _horrible_ at batching my suggestions I'm so sorry 🙈 🫠 but mostly formatting issues, so this should (hopefully) be the last round of edits!

2023-01-03 16:42 UTC, carolstran commented on sidebars.js
> +            description: 'How to create and configure various types of devices',
```suggestion
            description: 'How to create and configure various types of devices.',
```

2023-01-04 14:45 UTC, techwriter-dev commented on docs/quickstart/devices/android.md
> +# Android
@carolstran I'm fine with the text change, but I'm opposed to the use of the period because my intent with this front matter is to tweak the generated index page to have subtitles (which are typically not complete sentences):

![desc-used-as-subtitle](https://user-images.githubusercontent.com/49970529/210580280-448dc4a0-fa66-4140-94f1-03c71a18fa4e.png)

![desc-used-as-subtitles2](https://user-images.githubusercontent.com/49970529/210580376-6974f524-db74-4be7-96b8-450218903ad1.png)

2023-01-04 14:53 UTC, techwriter-dev commented on docs/quickstart/devices/cellular-modules.md
> +# Cellular modules
@carolstran Please see my reply and screenshots [above](https://github.com/EMnify/product-docs/pull/8#discussion_r1061556265).

2023-01-04 14:57 UTC, techwriter-dev commented on docs/quickstart/devices/android.md
> +# Android
Applying text change. See commit [ff8eb08f](https://github.com/EMnify/product-docs/pull/8/commits/f8eb08f551e89f9596c5d230a9ae0202f2d607b6) for details.

2023-01-04 15:00 UTC, techwriter-dev commented on docs/quickstart/troubleshooting.md
> +# Troubleshooting
@carolstran Please see my reply and screenshots https://github.com/EMnify/product-docs/pull/8#discussion_r1061556265.

2023-01-04 15:03 UTC, techwriter-dev commented on sidebars.js
> +            description: 'How to create and configure various types of devices',
This is actually functioning as a sentence, but only because Docusaurus won't allow me to format it as a heading.

2023-01-04 15:13 UTC, carolstran commented on docs/quickstart/devices/android.md
> +# Android
Next time, it'd be great if you could let me know these preferences earlier. All of the existing documentation merged follows this structure and you were the reviewer. I'm ok with changing our minds and redo-ing, but that extra work could've been prevented.

2023-01-04 15:20 UTC, techwriter-dev commented on docs/quickstart/troubleshooting.md
> +The event details will also show the data transmitted and the device status will be set to `Offline`.
@carolstran I'm also undecided on how to style event names, but I feel that some styling is better than no styling at all.

We can meet and discuss this when we actually have a concrete style guide to work on.

2023-01-04 15:43 UTC, techwriter-dev commented on docs/quickstart/devices/cellular-modules.md
> +`AT+CGDCONT=1,"IP","em",,`
Fixed AT command syntax highlighting problems on the "Cellular modules" page
Resolved in commit [fbb8126](https://github.com/EMnify/product-docs/pull/8/commits/fbb812687e07ac8d5e57eec129d6b0593947447f).

2023-01-04 15:53 UTC, techwriter-dev commented on docs/quickstart/devices/creating-a-device.md
> +# Creating a device
@carolstran Please see my comment and screenshots [above](https://github.com/EMnify/product-docs/pull/8#discussion_r1061556265).

2023-01-04 15:54 UTC, techwriter-dev commented on docs/quickstart/devices/getting-the-first-device-online.md
> +# Getting the first device online
@carolstran Please see my comment and screenshots [above](https://github.com/EMnify/product-docs/pull/8#discussion_r1061556265).

2023-01-04 16:02 UTC, techwriter-dev commented on docs/quickstart/devices/getting-the-first-device-online.md
> +[APN](#APN): `em` (or alternatively use `emnify`)
Corrected the link to APN on the "Getting the first device online" page:
Changes in commit [d9d7fff](https://github.com/EMnify/product-docs/pull/8/commits/d9d7fffb736fa771637b3269d5609595d9365be0)

2023-01-04 16:05 UTC, techwriter-dev commented on docs/quickstart/devices/gps-trackers.md
> +# GPS trackers
@carolstran Please see my comment and screenshots [above](https://github.com/EMnify/product-docs/pull/8#discussion_r1061556265).

2023-01-04 16:13 UTC, techwriter-dev commented on docs/quickstart/devices/gps-trackers.md
> +Where `0000` is the default SMS password.
IMO, user-provided form data  and passwords should be monospaced (like code).

2023-01-04 16:16 UTC, techwriter-dev commented on docs/quickstart/devices/gps-trackers.md
> +Both SMS and Superpassword can be changed and would then need to be replaced in the SMS command.
@carolstran I've never encountered `superpassword`. 

I know of `root password`, `superuser's password`, but this one is an enigma for me.

2023-01-05 06:40 UTC, techwriter-dev commented on docs/quickstart/devices/gps-trackers.md
> +For some Concox models (e.g. TR02) the password (default 666666) needs to be send with the command
Fixed password styling  for GPS trackers in commit [87da0a2](https://github.com/EMnify/product-docs/pull/8/commits/87da0a2d6aa448ed1a6b27d3fa479698b281941d).

2023-01-05 06:43 UTC, techwriter-dev commented on docs/quickstart/devices/gps-trackers.md
> +The default password is 123456. There are no spaces between gprs/APN and the password.
Fixed password styling  for GPS trackers in commit [87da0a2](https://github.com/EMnify/product-docs/pull/8/commits/87da0a2d6aa448ed1a6b27d3fa479698b281941d).

2023-01-05 06:43 UTC, techwriter-dev commented on docs/quickstart/devices/gps-trackers.md
> +Both SMS and Superpassword can be changed and would then need to be replaced in the SMS command.
Fixed password styling  for GPS trackers in commit [87da0a2](https://github.com/EMnify/product-docs/pull/8/commits/87da0a2d6aa448ed1a6b27d3fa479698b281941d).

2023-01-05 06:51 UTC, techwriter-dev commented on docs/quickstart/devices/cellular-modules.md
> +u-Blox supports the standard 3GPP command to set APNs via AT`+CGDCONT`
Resolved in [8fc76c9](https://github.com/EMnify/product-docs/pull/8/commits/8fc76c909c160afa18f4ebfe0865065ca6db2b91).

2023-01-05 06:51 UTC, techwriter-dev commented on docs/quickstart/devices/cellular-modules.md
> +According to [Quectel](https://www.quectel.com/faqs/12-8-what-is-the-difference-between-cgdcont-and-qicsgp/) the command AT+QICSGP shall be used when the internal TCP/UDP stack should be used – and i
Resolved in [8fc76c9](https://github.com/EMnify/product-docs/pull/8/commits/8fc76c909c160afa18f4ebfe0865065ca6db2b91).

2023-01-05 07:01 UTC, techwriter-dev commented on docs/quickstart/devices/industrial-routers.md
> +# Industrial routers
@carolstran Please see my comment and screenshots [above](https://github.com/EMnify/product-docs/pull/8#discussion_r1061556265).

2023-01-05 07:16 UTC, techwriter-dev commented on docs/quickstart/devices/industrial-routers.md
> +1. Teltonika Networks Router APN configuration via SMS console / API or Zapier [Teltonika Documentation Source](https://wiki.teltonika-networks.com/view/SMS_Commands)
Resolved in [e1b74a6](https://github.com/EMnify/product-docs/pull/8/commits/e1b74a614fe622d7cef09d4aa6f66b3a0b002d83).
Screenshot of original for reference: 
![teltonika-routers](https://user-images.githubusercontent.com/49970529/210723377-3a0cbeb1-9151-4782-94b9-aea3f1b0fd9b.png)

2023-01-05 07:21 UTC, techwriter-dev commented on docs/quickstart/devices/creating-a-device.md
> +title: Creating a device
They are not needed here. I removed them.

Resolved in [a49ed05](https://github.com/EMnify/product-docs/pull/8/commits/a49ed053ee02b55a74fa02f995eca7ea16c02215).

2023-01-05 07:23 UTC, techwriter-dev commented on docs/quickstart/devices/ios-devices.md
> +# iOS devices
@carolstran Please see my comment and screenshots [above](https://github.com/EMnify/product-docs/pull/8#discussion_r1061556265).

2023-01-05 07:27 UTC, techwriter-dev commented on docs/quickstart/registering-sims.md
> +description: Using your emnify account to register your SIMs
@carolstran Please see my comment and screenshots [above](https://github.com/EMnify/product-docs/pull/8#discussion_r1061556265).

2023-01-05 07:30 UTC, techwriter-dev commented
@carolstran All conversations have been resolved

2023-01-05 09:25 UTC, carolstran commented
@techwriter-dev Can you rebase with `main` before I review?

2023-01-06 10:15 UTC, carolstran requested changes
Most of my comments are not blocking, but there seem to be some merge conflict prompts left in Cloud Connect docs and that needs to be removed/resolved before merging.

After that, should be good to go 🚀

2023-01-06 10:15 UTC, carolstran commented on docs/services/cloud-connect.md
> +<<<<<<< HEAD
Looks like this page has some conflict issues left over in this file and needs to be cleaned up before merging 🧼

2023-01-06 10:15 UTC, carolstran commented on sidebars.js
> +            description: 'How to create and configure various types of devices.',
What did we decide re: punctuation on these descriptions? 

In this PR, you have one with punctuation (this line) and one without (line 40). I know we decided no punctuation for page descriptions, but I don't think we specifically decided on these 🤔 

My vote is punctuation on these as some have longer descriptions (e.g., SSO)

2023-01-06 14:17 UTC, techwriter-dev commented on docs/quickstart/getting-started.md
> +title: Getting started with emnify
@carolstran I am not opposed to the idea, but I'm still undecided about which approach would be best.

I'd like to have additional team feedback before changing this.

2023-01-06 15:06 UTC, techwriter-dev commented
@jeffstahlnecker Could please review and merge. Thanks!

2023-01-06 15:19 UTC, jeffstahlnecker approved these changes
Looks ready to go.

2023-01-06 15:30 UTC, techwriter-dev commented
Merging with @jeffstahlnecker's permission

2023-01-06 15:30 UTC, merged