First attempt at providing images with borders and rounding
emnify/product-docs pull request #83
Opened 2023-02-06 07:52 UTC by techwriter-dev

### Description

Aaron alluded to the benefit of adding borders to our images. This is especially important when screenshots contain text
above or below an image or diagram. In such cases, it can be difficult for the user to know where the image stops and the text of the page begins.

### Additional Context

The proposed CSS classes account for 3 situations
1. An unscaled image that could benefit from both image rounding with a rounded border
2. An image that already has a background color similar to the border color, which in such a case only needs rounding.
3. A large or scaled image that has a white background that only needs a rounded border. In larger images, image rounding is asymmetrical which doesn't look good.

2023-02-06 09:15 UTC, techwriter-dev commented
@carolstran I'm hoping you can evaluate the the **SMS** page within the context I provided in the PR description.

I'm sure there is a more elegant solution than having to use 3 different classes and the need to make a decision on which category an image falls into.

2023-02-06 09:16 UTC, techwriter-dev commented
@carolstran I'm hoping you can evaluate the the **SMS** page within the context I provided in the PR description.

I'm sure there is a more elegant solution than having to use 3 different classes and the need to make a decision on which category an image falls into.

2023-02-07 07:29 UTC, carolstran commented
@techwriter-dev Have you run this by the design team for review? I think it'd be useful to get their insights on it before we decide exactly how to implement 👨🏼‍🎨  

💡  We can discuss this together today, but something I thought could be cool to use some of the green shades from the new branding for the border color 👀 It could be a nice way to bring some color in and use those shades that are fun, but not accessible enough to use in another part of the UI.

Here's an example using the `#4ee794` value:
<img width="1509" alt="Screenshot 2023-02-07 at 08 27 29" src="https://user-images.githubusercontent.com/26869552/217177830-f8a96934-4035-49ae-bf4d-2e4998dc745e.png">

But again, this is the design team's call so let's consult them!

2023-02-14 07:56 UTC, techwriter-dev commented
> But again, this is the design team's call so let's consult them!

Requested feedback from Aaron in Slack.

2023-02-15 13:31 UTC, carolstran requested changes

2023-02-15 13:31 UTC, carolstran commented on src/css/custom.css
> +}
Following our conversation in the sync, can we open a ticket for the code snippets and handle it separately? It'll require more discussion on how we want to approach this, as well as looking into [other theming options](https://github.com/FormidableLabs/prism-react-renderer/tree/master/src/themes). 

I agree that there are opportunities to use more color 🎨 ✨  but I wouldn't feel comfortable merging this at the moment because the green causes some issues with the existing syntax highlighting:
<img width="760" alt="Screenshot 2023-02-15 at 14 17 34" src="https://user-images.githubusercontent.com/26869552/219040263-5afbae22-fd44-4bbf-847b-41500c24cf17.png">

2023-02-15 13:31 UTC, carolstran commented on src/css/custom.css
> +}
Are we planning to add a border to all screenshots and infographics? If yes, then we can consider adding it to `img` tags within `.theme-doc-markdow` (for example)

That way, we wouldn't have to remember to add the class manually each time (and then we could still use the markdown syntax when possible) 😊

2023-02-16 11:53 UTC, techwriter-dev commented on src/css/custom.css
> +}
@carolstran In that case, I recommend we use it only for the inline code, not for code blocks, i.e., we would retain this:

```
/* inline code */
code {
  color: #005f0f;
}
```

2023-02-16 16:37 UTC, carolstran commented on src/css/custom.css
> +}
I would still strongly prefer us moving this to a separate PR as it's out of scope for this PR and requires more discussion/design review 😬 Would you be ok with that?

2023-02-16 16:51 UTC, carolstran commented on src/css/custom.css
> +}
As we discussed this morning, I did some experimenting 🧪 and here's a solution we could consider:

```suggestion
/* Add border to screenshots */
.theme-doc-markdown img:not(.infographic) {
  border: 1px solid #e4e4e4; /* ui-grey-80 */
  border-radius: 5px;
}

/* Remove border from img tags within tables */
.theme-doc-markdown table tr td img {
  border: none !important;
}
```

It's sliiiiightly cursed syntax 💀 but it:
- First block adds borders to all `img` tags within the main content except any with the `infographic` class 
  - 🖌️  Used the [`:not()` CSS pseudo-class](https://caniuse.com/css-not-sel-list) for this
- Second block ensures that any `img` tags displayed within tables (like the [User Management](https://docs.emnify.com/services/user-management) one)  don't have a border 
  - 🖌️  Unfortunately descendant combinators are difficult to cover with `:not()` bc there are multiple paths to select the element

That said, we could consider keeping the borders on infographics, as it's a nice way to differentiate those from the surrounding content:

<details>
<summary>Examples: Infographics with border</summary>
<img width="543" alt="Screenshot 2023-02-16 at 17 33 45" src="https://user-images.githubusercontent.com/26869552/219431316-d90970da-818a-4ae7-9e39-16b7100be957.png">

This one may need additional padding, but you get the idea:
<img width="557" alt="Screenshot 2023-02-16 at 17 35 21" src="https://user-images.githubusercontent.com/26869552/219431332-89089af7-1092-40ab-9ced-edd6f6f98796.png">
</details>

Let me know what you think!

2023-02-17 07:57 UTC, techwriter-dev commented on src/css/custom.css
> +}
@carolstran Agreed.

2023-02-20 11:01 UTC, techwriter-dev commented
@carolstran I think macOS window screenshots would look better without the default border (see SSO Microsoft AD), but I'll leave that decision to you.

2023-02-20 14:07 UTC, carolstran requested changes
Sooooo close, just some cleanup required based on our previous discussions then we should be good 🕺🏼

2023-02-20 14:07 UTC, carolstran commented on docs/services/sms.md
> +/>
The changes in this file can probably be reverted since we're no longer using classes, right?

2023-02-20 14:07 UTC, carolstran commented on src/css/custom.css
> +
Looks like this still needs to be removed 🤔  (as discussed in the other convo about moving these changes to a new PR)

2023-02-20 14:07 UTC, carolstran commented on src/css/custom.css
> +.theme-doc-markdown img:not(.infographic) {
Did we decide to keep the border on all images? If yes then we can remove the `:not` pseudo class:

```suggestion
.theme-doc-markdown img {
```

Or alternatively, we can add a more general class for removing the border. For example:

```suggestion
.theme-doc-markdown img:not(.no-border) {
```

Then add the class for this.

☝🏼 Thinking about this because I saw your comment about the SSO screenshots. IMO those should be cleaned up eventually anyway... but this could be a good temp fix for this!

2023-02-22 14:52 UTC, carolstran approved these changes
🚀 🧑‍🎨 ✨

2023-02-23 08:13 UTC, merged