Publish updated Data Streamer documentation
EMnify/product-docs pull request #9
Opened 2022-12-23 11:39 UTC by carolstran

Finally getting the new Data Streamer documentation up 🎉 

What's included in this PR ✨ 
- ✅  Introduction page explaining what the data streamer is and the benefits
- ✅  Explanation of connection types
- ✅  Explanation of stream types
- ✅  Guide for managing data streams 
- ✅  Usage documentation covering the Portal and API
- ❌  Removed the integration guides category (out of scope and conflicts with the added materials)
- ❌  Removed the Data Streamer section from the current Services page (these docs replace those)

_**⚠️ Note: Majority of this content was written by Viktoria (SME) and I reviewed for language/clarity.**_ 

Next steps (in future, separate PRs) 🛸 
- Anonymized sample JSON responses for usage data 
- Links to the new events docs (once #10  is merged)
- Relevant screenshots for guides (with new Portal branding)

Internal ticket 🎟️  [SDOCS-12](https://emnify.atlassian.net/browse/SDOCS-12)

2022-12-27 10:16 UTC, techwriter-dev commented on docs/data-streamer/available-integrations.md
> +The data streamer may also send usage and event data in JSON format to a configurable webhook URL specified by the user.
I'm wondering if avoiding the passive construction might be better:
```
The data streamer may also send usage and event data in JSON format to a configurable, user-specified webhook URL.
```

2022-12-27 10:21 UTC, techwriter-dev commented on docs/data-streamer/using-the-data-streamer.md
> +Data streams are marked as **Running** are properly operating, failed streams have the **Error** status, and paused streams are marked as **Paused**.
This works as it is, but I would have avoided the compound sentence, keeping it as simple as possible:
```
Data streams are marked as **Running** are properly operating.
Failed streams exhibit an **Error** status.
Paused streams are marked as **Paused**.
```

2022-12-27 10:29 UTC, techwriter-dev commented on docs/data-streamer/stream-types.md
> +- **Input for custom billing systems** (i.e. updating billing configuration, processing invoices, etc.)
Needs a comma:
```
- **Input for custom billing systems** (i.e., updating billing configuration, processing invoices, etc.)
```

2022-12-27 10:44 UTC, techwriter-dev commented on docs/data-streamer/using-the-data-streamer.md
> +Available entry points are listed under the [**Integrations** section of the emnify Swagger API reference](https://cdn.emnify.net/api/doc/swagger.html#/Integrations).
I would have hyperlinked only "Integrations" and avoided the reference to "Swagger" since it is not visible in the page/document title, but this is only my "minimalist" preference:
```
Available entry points are listed under the [Integrations](https://cdn.emnify.net/api/doc/swagger.html#/Integrations) section of the emnify REST API reference.
```
The external page's title ([EMnify Rest API 1.3](https://cdn.emnify.net/api/doc/swagger.html)) needs updating since [REST](https://www.techtarget.com/searchapparchitecture/definition/REST-REpresentational-State-Transfer) as an acronym should be all uppercase.

2022-12-27 11:00 UTC, techwriter-dev commented on docs/data-streamer/using-the-data-streamer.md
> +Please refer to the [Getting Started guide in the emnify API Documentation](https://cdn.emnify.net/api/doc/getting-started.html) for detailed instructions.
Same as above: I would have constructed the hyperlink like this:

```
Please refer to the *emnify System Documentation* [Getting Started](https://cdn.emnify.net/api/doc/getting-started.html) guide for detailed instructions.
```
I treat complete sets of documentation like standalone publications, e.g., books, films, etc., that are typically set in italics. But, there is also the issue of the title itself. What is the real name of this documentation?
![system-or-api-docs](https://user-images.githubusercontent.com/49970529/209656888-9fc17980-0249-41fa-8363-2653427d9d00.png)

2022-12-27 11:08 UTC, techwriter-dev commented on docs/data-streamer/using-the-data-streamer.md
> +That said, [understanding how an OpenAPI Specification is structured](https://oai.github.io/Documentation/specification.html) could help you navigate our documentation.
In a blog, I might use "that being said". However, Grammarly doesn't like my passive construction.

Grammarly also considers the sentence as it currently stands too "wordy".  Using "nevertheless" instead passes Grammarly's inspection with flying colors:

```
Nevertheless, [understanding how an OpenAPI Specification is structured](https://oai.github.io/Documentation/specification.html) could help you navigate our documentation.
```

2022-12-27 13:14 UTC, techwriter-dev commented on docs/data-streamer/using-the-data-streamer.md
> +Details on setting up, updating, or deleting integrations are in the [emnify Swagger API reference](https://cdn.emnify.net/api/doc/swagger.html#/Integrations).
Same as my comment on line 83 above.

Read Swagger's on answer to "[What Is the Difference Between Swagger and OpenAPI?](https://swagger.io/blog/api-strategy/difference-between-swagger-and-openapi/)" which they dedicated an entire blog post to!
> ... it was [donated to the OpenAPI Initiative by SmartBear Software](https://smartbear.com/news/news-releases/smartbear-launches-open-api-initiative-with-key-in/) and renamed from the Swagger Specification to OpenAPI specification in 2015.

So, when I see this, I'm confused:
![swagger-or-openapi](https://user-images.githubusercontent.com/49970529/209671731-9bc7b934-e822-48f5-b367-60aa9cfddcef.png)

2022-12-27 13:18 UTC, techwriter-dev commented on docs/data-streamer/available-integrations.md
> +**_Warning: This guide uses a legacy version of the emnify Portal._**
This is OK, but I would not have had any objections to another[ "Caution" admonition](https://docusaurus.io/docs/markdown-features/admonitions) immediately after the "Tip" admonition.

2022-12-27 19:32 UTC, carolstran commented on docs/data-streamer/using-the-data-streamer.md
> +Available entry points are listed under the [**Integrations** section of the emnify Swagger API reference](https://cdn.emnify.net/api/doc/swagger.html#/Integrations).
Keeping the linked text as-is as descriptive linking is more accessible, but great catch/call on "Swagger" 💯  

Thanks for flagging and also linking the references! Super helpful.

2022-12-27 19:41 UTC, carolstran commented on docs/data-streamer/using-the-data-streamer.md
> +Please refer to the [Getting Started guide in the emnify API Documentation](https://cdn.emnify.net/api/doc/getting-started.html) for detailed instructions.
That's a great question, I supposed we can determine what we want to call it 🤔 

I'd lean towards *emnify REST API documentation* - what do you think?

2022-12-28 20:38 UTC, techwriter-dev commented on docs/data-streamer/using-the-data-streamer.md
> +Please refer to the [Getting Started guide in the emnify API Documentation](https://cdn.emnify.net/api/doc/getting-started.html) for detailed instructions.
We'll have to figure it later. Following the [</> Swagger API Reference](https://cdn.emnify.net/api/doc/swagger.html) link reveals the actual API docs that has a completely different title (**EMnify Rest API**). I wonder how anyone can effectively communicate about these pages when using their names instead of URLs.

2022-12-28 21:21 UTC, techwriter-dev commented on sidebars.js
> +        },
This "Getting Starting" `index` nav item duplicates the parent "Data Streamer" nav with the same "index" anchor.
```suggestion
```
The result is confusing for the first-time visitor who might assume that the next page, "emnify multicloud Data Streamer" might be some different (or enhanced) data streamer:
![datastreamer-nav-problems](https://user-images.githubusercontent.com/49970529/209873235-1dfc0746-343d-4852-a023-66113c1e55a3.png)

## Removing this extraneous nav item fixes the problem
![datastreamer-nav-fix](https://user-images.githubusercontent.com/49970529/209873300-3534eb30-e6c5-4a57-b66b-77b37cb240c6.png)

2022-12-28 21:30 UTC, techwriter-dev commented on docs/data-streamer/managing-data-streams.md
> +You can pause a stream (e.g., if you want to take down the receiving server for maintenance) and resume once convenient by activating the data stream again via your preferred interface.
Maybe it's just me, but I thought this sounds a little better. You can leave as is if you like.

```suggestion
You can pause a stream (e.g., if you want to take down the receiving server for maintenance) and resume later when convenient by activating the data stream again via your preferred interface. 
```

2022-12-28 21:33 UTC, techwriter-dev commented on docs/data-streamer/usage.md
> +Data streams are managed by using the [emnify Portal](#data-streamer-in-the-portal) or the [Data Streamer API](#data-streamer-api).
```suggestion
You can manage data streams with the [emnify Portal](#data-streamer-in-the-portal) or the [Data Streamer API](#data-streamer-api).
```

2022-12-28 21:35 UTC, techwriter-dev commented on docs/data-streamer/usage.md
> +To [manage your data streams](managing-data-streams), log in to your account on the [emnify Portal](https://portal.emnify.com/).
```suggestion
To [manage your data streams](managing-data-streams), log in to your [emnify Portal](https://portal.emnify.com/) account. 
```

2022-12-28 21:37 UTC, carolstran commented on sidebars.js
> +        },
Ah good catch thank you! I definitely want it to show up in the sidebar (all necessary/important pages should be IMO) but I'll reconfigure the sidebar so the page isn't duplicated.

I'll also update this on my other two PRs (#10 and #12) 🔎

2022-12-28 21:47 UTC, techwriter-dev commented on docs/data-streamer/usage.md
> +Then, navigate to the **Integrations** page by clicking the **Integrations** menu item on the sidebar.
I know this is getting kind of picky, but when it comes to things like this ("on" vs "in") I typically go with the choice that returns the most Google results:
- [on the sidebar ](https://www.google.com/search?q=%22on+the+sidebar%22) yields 14.1 million
- [in the sidebar](https://www.google.com/search?q=%22in+the+sidebar%22)  yields 19.2 million (plus [Cambridge Dictionary's approval](https://dictionary.cambridge.org/dictionary/english/sidebar))
```suggestion
Then, navigate to the **Integrations** page by clicking the **Integrations** menu item in the sidebar.
```

2022-12-28 21:50 UTC, techwriter-dev commented on docs/data-streamer/usage.md
> +Once authenticated, users can create data streams by making `POST` requests to `/api/v2/data_stream`.
```suggestion
Once authenticated, users can create data streams by sending `POST` requests to `/api/v2/data_stream`. 
```

2022-12-28 21:51 UTC, techwriter-dev commented on docs/data-streamer/usage.md
> +You can list all data streams belonging to your organization by making `GET` requests to `/api/v2/data_stream`.
```suggestion
You can list all data streams belonging to your organization by sending `GET` requests to `/api/v2/data_stream`. 
```

2022-12-28 21:53 UTC, techwriter-dev commented on docs/data-streamer/usage.md
> +Making a `DELETE` request to `/api/v2/data_stream/{data_stream_id}` will delete the data stream with that ID.
```suggestion
Sending a `DELETE` request to `/api/v2/data_stream/{data_stream_id}` will delete the data stream with that ID.
```

2022-12-28 22:01 UTC, techwriter-dev commented on docs/data-streamer/available-integrations.md
> +Amazon Kinesis Data Streams allows for collecting and processing large streams of event and usage data records in real-time.
According to [Merriam-Webster](https://www.merriam-webster.com/dictionary/real%20time), the noun form is not hyphenated: *real time*. 
![mw-in-real-time](https://user-images.githubusercontent.com/49970529/209876622-34676e21-baae-4f75-a492-a8e4ea8cf9a3.png)


```suggestion
Amazon Kinesis Data Streams allows for collecting and processing large streams of event and usage data records in real time. 
```

2022-12-28 22:02 UTC, techwriter-dev commented on docs/data-streamer/available-integrations.md
> +Pub/Sub is Google’s messaging middleware that allows you to collect and process your event and usage data in real-time.
```suggestion
Pub/Sub is Google’s messaging middleware that allows you to collect and process your event and usage data in real time. 
```

2022-12-28 22:02 UTC, techwriter-dev commented on docs/data-streamer/available-integrations.md
> +Google Cloud BigQuery is a data warehouse that enables you to query your connectivity metadata in real-time to gain insights and predict business outcomes.
```suggestion
Google Cloud BigQuery is a data warehouse that enables you to query your connectivity metadata in real time to gain insights and predict business outcomes.
```

2022-12-28 22:02 UTC, techwriter-dev commented on docs/data-streamer/index.md
> +With the emnify Data Streamer, this connectivity metadata is made available to your cloud platform or self-developed software stacks in near real-time.
```suggestion
With the emnify Data Streamer, this connectivity metadata is made available to your cloud platform or self-developed software stacks in near real time. 
```

2022-12-28 22:10 UTC, techwriter-dev requested changes
@carolstran I completed my review and was able to add suggestions this time. Most of them are very minor.

The only ones that really need to be applied are in order of importance:

1. The problematic extraneous nav item in `sidebars.js`
2. The noun usage of "in real time"

Otherwise it looks great! I liked the way you chose to override the default admonition headings.

2022-12-28 22:41 UTC, carolstran commented on sidebars.js
> +        },
Update! TIL that Docusaurus has a [generated index pages](https://docusaurus.io/docs/sidebar/items#category-link) so I implemented that in https://github.com/EMnify/product-docs/pull/9/commits/5283193526dbaf6b91b7023facf1c53fe0abb582 and attached a screenshot to this comment. 

<img width="1272" alt="Screenshot 2022-12-28 at 23 36 01" src="https://user-images.githubusercontent.com/26869552/209881496-fdfbe65a-9492-4d02-928b-9277eddd32ae.png">

IMO it looks nice, it's easy to generate, and it's a consistent way to summarize the contents within a category.

If you think this looks ok then I'll add it to the other PRs as well 🚀

2022-12-29 06:57 UTC, ChristianHenkeEMnify reviewed
Integromat naming has been changed to make. We need to update it here and in the guide.

2022-12-29 06:59 UTC, ChristianHenkeEMnify commented on docs/data-streamer/available-integrations.md
> +Pub/Sub is Google’s messaging middleware that allows you to collect and process your event and usage data in real-time.
Hm throughout the doc consistently real-time is used

2022-12-30 17:52 UTC, techwriter-dev commented
@carolstran Why is GitHub showing that I haven't reviewed this PR?

![pr9-still-showing-review-requested](https://user-images.githubusercontent.com/49970529/210098813-92e46a85-b7bf-4aa3-b450-6c3e3d3a936e.png)

The existence of a **Dismiss review** option implies that I reviewed it:

![dismss-review-implies-that-i-reviewed-it](https://user-images.githubusercontent.com/49970529/210098958-d584b771-22f2-46f6-b6e5-dd08f10ccbb9.png)

2022-12-30 21:23 UTC, carolstran commented
@techwriter-dev I re-requested your review once I applied the changes you suggested since I need an approval to merge 😇

2023-01-01 19:03 UTC, techwriter-dev commented on sidebars.js
> +        type: 'generated-index',
@carolstran This is a nice addition for enhancing the UI.

Maybe there's a way to configure another image/icon instead of the default (perhaps [`link.image`](https://docusaurus.io/docs/next/sidebar/items#generated-index-page)), but it's not that urgent.

2023-01-01 19:04 UTC, techwriter-dev approved these changes
@carolstran The generated index looks nice.

2023-01-01 20:52 UTC, merged