Mention the initial pre-paid credit in the Quickstart guide
emnify/product-docs pull request #95
Opened 2023-02-21 15:01 UTC by carolstran

### Description

Growth squad has a ticket about communicating the initial 10 $/€ of pre-paid credit 🤑  This number is consistent for all new accounts, so it makes sense to add it to the documentation. I used the emnify Terms of Service to determine specifics about that amount. 

### Additional Context

Internal ticket 🎟️  [PGR-203](https://emnify.atlassian.net/browse/PGR-203)

2023-02-22 10:55 UTC, techwriter-dev requested changes
A minor change to make things more concise and a minor correction.

2023-02-22 10:55 UTC, techwriter-dev commented on docs/quickstart/getting-started.md
> +The package also includes an initial 10 EUR or USD of pre-paid credit to help you test emnify's services.
Actually, I question the need for including "prepaid" at all.
Grammarly is fine with this:

> This package includes a 10 EUR/USD credit for testing emnify's services.

```suggestion
This package includes a prepaid credit of 10 EUR/USD for testing emnify's services.
```

2023-02-22 10:55 UTC, techwriter-dev commented on docs/quickstart/getting-started.md
> +To get your free Evaluation SIM package, [log into your emnify account](https://portal.emnify.com/sign) and follow these steps:
```suggestion
To get your free Evaluation SIM package, [log in to your emnify account](https://portal.emnify.com/sign) and follow these steps:
```
**login** (noun) vs **log in** (verb) thus  [... log in to ...](https://www.express.co.uk/life-style/science-technology/996184/Gmail-sign-in-how-to-log-in-Gmail-account-easy-create-Gmail-email).

2023-02-22 14:59 UTC, carolstran commented
@techwriter-dev Oh sorry! I didn't ping you for a review yet because it still needs to be reviewed by Bas. Next time I'll make sure to add a note, but in the meantime, I can apply your suggestions 😊

2023-03-01 09:04 UTC, techwriter-dev requested changes
Some corrections are still needed.

2023-03-01 09:04 UTC, techwriter-dev commented on docs/quickstart/getting-started.md
> +To get your free Evaluation SIM package, [log into your emnify account](https://portal.emnify.com/sign) and follow these steps:
This is still not resolved.

Correct: *log* **in to** *your emnify account*

Perhaps these [Quora answers](https://www.quora.com/Which-one-is-correct-Log-in-to-your-account-Login-into-your-account-Log-in-your-account-or-Log-into-your-account-Ive-seen-people-using-all-of-them-and-Im-a-bit-confused) can explain it more clearly.

2023-03-01 10:16 UTC, carolstran commented
@techwriter-dev My bad, thought I batched before 🤦🏼‍♀️  Should be ready now!

2023-03-01 13:12 UTC, techwriter-dev approved these changes
Perfect!

2023-03-01 13:50 UTC, merged